// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/addresses/data/repository_imp/user_addresses_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/features/addresses/data/data_source/user_addresses_remote_data_source.dart'
    as _i3;
import 'package:flower_app/features/addresses/data/model/user_addresses_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserAddressesDTO_0 extends _i1.SmartFake
    implements _i2.UserAddressesDTO {
  _FakeUserAddressesDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserAddressesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserAddressesRemoteDataSource extends _i1.Mock
    implements _i3.UserAddressesRemoteDataSource {
  MockUserAddressesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserAddressesDTO> getUserAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getUserAddresses,
          [],
        ),
        returnValue:
            _i4.Future<_i2.UserAddressesDTO>.value(_FakeUserAddressesDTO_0(
          this,
          Invocation.method(
            #getUserAddresses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserAddressesDTO>);

  @override
  _i4.Future<_i2.UserAddressesDTO> deleteUserAddress(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserAddress,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.UserAddressesDTO>.value(_FakeUserAddressesDTO_0(
          this,
          Invocation.method(
            #deleteUserAddress,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.UserAddressesDTO>);
}
