name: flower_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  injectable:
  get_it:
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  equatable:
  flutter_easyloading:
  shared_preferences:
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  dio:
  internet_connection_checker: ^3.0.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  json_serializable: ^6.8.0
  mockito: ^5.4.5
  injectable_generator:
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/image/
  fonts:
    - family: IM FELL English
      fonts:
        - asset: assets/fonts/IMFellEnglish-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf