name: flower_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc_test: ^10.0.0
  dio: ^5.0.0  # Specify the correct version for dio
  equatable: ^2.0.0  # Specify the correct version for equatable
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  flutter_easyloading: ^3.0.0  # Specify the correct version for flutter_easyloading
  get_it: ^8.0.0  # Specify the correct version for get_it
  injectable: ^2.1.0  # Specify the correct version for injectable
  internet_connection_checker: ^3.0.1
  skeletonizer: ^1.4.3
  json_annotation: ^4.9.0
  mockito: ^5.4.5
  retrofit: ^4.4.2
  shared_preferences: ^2.0.15  # Specify the correct version for shared_preferences
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  provider: ^6.1.4
  intl: ^0.19.0
  flutter_intl: ^0.0.1
  flutter_localization: ^0.3.2

dev_dependencies:
  intl_utils: ^2.8.10
  build_runner: ^2.3.3  # Specify the correct version for build_runner
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.0  # Specify the correct version for injectable_generator
  json_serializable: ^6.8.0
  mockito: ^5.4.5
  retrofit_generator: ^9.0.0 # for Dart 3.3 use ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
  fonts:
    - family: IM FELL English
      fonts:
        - asset: assets/fonts/IMFellEnglish-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_intl:
  enabled: true
