name: flower_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc_test: ^10.0.0
  dio: null
  equatable: null
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_bloc: ^9.1.0
  flutter_easyloading: null
  get_it: null
  injectable: null
  internet_connection_checker: ^3.0.1
  skeletonizer: ^1.4.3
  json_annotation: ^4.9.0
  mockito: ^5.4.5
  retrofit: ^4.4.2
  shared_preferences: null
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  provider: ^6.1.4
  flutter_localization: ^0.3.2
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  mime: ^2.0.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  geocoding: ^3.0.0
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: null
  json_serializable: ^6.8.0
  mockito: ^5.4.5
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/svg/
    - assets/
    - assets/map_styles/
    - assets/
  fonts:
    - family: IM FELL English
      fonts:
        - asset: assets/fonts/IMFellEnglish-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
flutter_intl:
  enabled: true
