// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/categories/data/data_source/categories_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:flower_app/core/api/api_client.dart' as _i13;
import 'package:flower_app/features/auth/data/model/forget_response_password_dto.dart'
    as _i4;
import 'package:flower_app/features/auth/data/model/reset_password_dto.dart'
    as _i6;
import 'package:flower_app/features/auth/data/model/sign_up_response_dto.dart'
    as _i2;
import 'package:flower_app/features/auth/data/model/verify_email_response_dto.dart'
    as _i5;
import 'package:flower_app/features/auth/domain/entity/sign_in_request.dart'
    as _i16;
import 'package:flower_app/features/auth/domain/entity/sign_up_request.dart'
    as _i15;
import 'package:flower_app/features/home/best_seller_products/data/model/BestSellerProductsModel.dart'
    as _i17;
import 'package:flower_app/features/home/categories/data/model/categories_response_model.dart'
    as _i11;
import 'package:flower_app/features/home/categories/data/model/specific_categories_response_model.dart'
    as _i12;
import 'package:flower_app/features/home/home_tab/data/model/category_response_dto.dart'
    as _i7;
import 'package:flower_app/features/home/home_tab/data/model/occasion_response_dto.dart'
    as _i8;
import 'package:flower_app/features/home/occasions/data/model/occasions_dto.dart'
    as _i9;
import 'package:flower_app/features/home/occasions/data/model/products_response_dto.dart'
    as _i10;
import 'package:flower_app/features/home/products_details/data/models/products_details_models.dart'
    as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseDTO_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDTO {
  _FakeSignUpResponseDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetResponsePasswordDto_2 extends _i1.SmartFake
    implements _i4.ForgetResponsePasswordDto {
  _FakeForgetResponsePasswordDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyEmailResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyEmailResponseDto {
  _FakeVerifyEmailResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDTO_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDTO {
  _FakeResetPasswordResponseDTO_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryResponseDTO_5 extends _i1.SmartFake
    implements _i7.CategoryResponseDTO {
  _FakeCategoryResponseDTO_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOccasionResponseDTO_6 extends _i1.SmartFake
    implements _i8.OccasionResponseDTO {
  _FakeOccasionResponseDTO_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOccasionsResponseDTO_7 extends _i1.SmartFake
    implements _i9.OccasionsResponseDTO {
  _FakeOccasionsResponseDTO_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponseDTO_8 extends _i1.SmartFake
    implements _i10.ProductsResponseDTO {
  _FakeProductsResponseDTO_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponseModel_9 extends _i1.SmartFake
    implements _i11.CategoriesResponseModel {
  _FakeCategoriesResponseModel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpecificCategoriesResponseModel_10 extends _i1.SmartFake
    implements _i12.SpecificCategoriesResponseModel {
  _FakeSpecificCategoriesResponseModel_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i13.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i2.SignUpResponseDTO> signUp(_i15.SignUpRequest? data) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [data]),
            returnValue: _i14.Future<_i2.SignUpResponseDTO>.value(
              _FakeSignUpResponseDTO_0(
                this,
                Invocation.method(#signUp, [data]),
              ),
            ),
          )
          as _i14.Future<_i2.SignUpResponseDTO>);

  @override
  _i14.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>> signIn(
    _i16.SignInRequest? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [data]),
            returnValue:
                _i14.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>.value(
                  _FakeHttpResponse_1<_i2.SignUpResponseDTO>(
                    this,
                    Invocation.method(#signIn, [data]),
                  ),
                ),
          )
          as _i14.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>);

  @override
  _i14.Future<_i4.ForgetResponsePasswordDto> forgetPassword(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [data]),
            returnValue: _i14.Future<_i4.ForgetResponsePasswordDto>.value(
              _FakeForgetResponsePasswordDto_2(
                this,
                Invocation.method(#forgetPassword, [data]),
              ),
            ),
          )
          as _i14.Future<_i4.ForgetResponsePasswordDto>);

  @override
  _i14.Future<_i5.VerifyEmailResponseDto> verifyEmail(
    Map<String, String>? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [code]),
            returnValue: _i14.Future<_i5.VerifyEmailResponseDto>.value(
              _FakeVerifyEmailResponseDto_3(
                this,
                Invocation.method(#verifyEmail, [code]),
              ),
            ),
          )
          as _i14.Future<_i5.VerifyEmailResponseDto>);

  @override
  _i14.Future<_i6.ResetPasswordResponseDTO> resetPassword(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [data]),
            returnValue: _i14.Future<_i6.ResetPasswordResponseDTO>.value(
              _FakeResetPasswordResponseDTO_4(
                this,
                Invocation.method(#resetPassword, [data]),
              ),
            ),
          )
          as _i14.Future<_i6.ResetPasswordResponseDTO>);

  @override
  _i14.Future<_i3.HttpResponse<_i17.BestSellerProductsModel>> getBestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSeller, []),
            returnValue: _i14.Future<
              _i3.HttpResponse<_i17.BestSellerProductsModel>
            >.value(
              _FakeHttpResponse_1<_i17.BestSellerProductsModel>(
                this,
                Invocation.method(#getBestSeller, []),
              ),
            ),
          )
          as _i14.Future<_i3.HttpResponse<_i17.BestSellerProductsModel>>);

  @override
  _i14.Future<_i7.CategoryResponseDTO> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i14.Future<_i7.CategoryResponseDTO>.value(
              _FakeCategoryResponseDTO_5(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i14.Future<_i7.CategoryResponseDTO>);

  @override
  _i14.Future<_i8.OccasionResponseDTO> getOccasion() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasion, []),
            returnValue: _i14.Future<_i8.OccasionResponseDTO>.value(
              _FakeOccasionResponseDTO_6(
                this,
                Invocation.method(#getOccasion, []),
              ),
            ),
          )
          as _i14.Future<_i8.OccasionResponseDTO>);

  @override
  _i14.Future<_i9.OccasionsResponseDTO> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i14.Future<_i9.OccasionsResponseDTO>.value(
              _FakeOccasionsResponseDTO_7(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i14.Future<_i9.OccasionsResponseDTO>);

  @override
  _i14.Future<_i10.ProductsResponseDTO> getProductsByOccasion(
    String? occasionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByOccasion, [occasionId]),
            returnValue: _i14.Future<_i10.ProductsResponseDTO>.value(
              _FakeProductsResponseDTO_8(
                this,
                Invocation.method(#getProductsByOccasion, [occasionId]),
              ),
            ),
          )
          as _i14.Future<_i10.ProductsResponseDTO>);

  @override
  _i14.Future<_i3.HttpResponse<_i18.ProductsDetailsModels>> getProductDetails(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [id]),
            returnValue:
                _i14.Future<_i3.HttpResponse<_i18.ProductsDetailsModels>>.value(
                  _FakeHttpResponse_1<_i18.ProductsDetailsModels>(
                    this,
                    Invocation.method(#getProductDetails, [id]),
                  ),
                ),
          )
          as _i14.Future<_i3.HttpResponse<_i18.ProductsDetailsModels>>);

  @override
  _i14.Future<_i11.CategoriesResponseModel> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i14.Future<_i11.CategoriesResponseModel>.value(
              _FakeCategoriesResponseModel_9(
                this,
                Invocation.method(#getAllCategories, []),
              ),
            ),
          )
          as _i14.Future<_i11.CategoriesResponseModel>);

  @override
  _i14.Future<_i12.SpecificCategoriesResponseModel> getSpecificCategory(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecificCategory, [categoryId]),
            returnValue:
                _i14.Future<_i12.SpecificCategoriesResponseModel>.value(
                  _FakeSpecificCategoriesResponseModel_10(
                    this,
                    Invocation.method(#getSpecificCategory, [categoryId]),
                  ),
                ),
          )
          as _i14.Future<_i12.SpecificCategoriesResponseModel>);
}
