// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/main_profile_screen/data/data_source/profile_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:dio/dio.dart' as _i24;
import 'package:flower_app/core/api/api_client.dart' as _i16;
import 'package:flower_app/features/auth/data/model/forget_response_password_dto.dart'
    as _i5;
import 'package:flower_app/features/auth/data/model/reset_password_dto.dart'
    as _i7;
import 'package:flower_app/features/auth/data/model/sign_up_response_dto.dart'
    as _i3;
import 'package:flower_app/features/auth/data/model/verify_email_response_dto.dart'
    as _i6;
import 'package:flower_app/features/auth/domain/entity/sign_in_request.dart'
    as _i19;
import 'package:flower_app/features/auth/domain/entity/sign_up_request.dart'
    as _i18;
import 'package:flower_app/features/cart/data/models/create_cart_reponse.dart'
    as _i25;
import 'package:flower_app/features/cart/data/models/create_cart_request.dart'
    as _i26;
import 'package:flower_app/features/cart/data/models/delet_cart_item_dto/delete_cart_response_dto.dart'
    as _i27;
import 'package:flower_app/features/cart/data/models/update_product_quantity/update_cart_quantity_request.dart'
    as _i29;
import 'package:flower_app/features/cart/data/models/update_product_quantity/update_cart_quantity_response_dto.dart'
    as _i28;
import 'package:flower_app/features/cart/data/models/user_cart_response/user_cart_response_model.dart'
    as _i15;
import 'package:flower_app/features/checkout/data/model/addresses_response_dto.dart'
    as _i30;
import 'package:flower_app/features/home/best_seller_products/data/model/BestSellerProductsModel.dart'
    as _i20;
import 'package:flower_app/features/home/categories/data/model/categories_response_model.dart'
    as _i12;
import 'package:flower_app/features/home/categories/data/model/specific_categories_response_model.dart'
    as _i13;
import 'package:flower_app/features/home/home_tab/data/model/category_response_dto.dart'
    as _i8;
import 'package:flower_app/features/home/home_tab/data/model/occasion_response_dto.dart'
    as _i9;
import 'package:flower_app/features/home/occasions/data/model/occasions_dto.dart'
    as _i10;
import 'package:flower_app/features/home/occasions/data/model/products_response_dto.dart'
    as _i11;
import 'package:flower_app/features/home/products_details/data/models/products_details_models.dart'
    as _i21;
import 'package:flower_app/features/profile/main_profile_screen/data/model/change_password_model.dart'
    as _i14;
import 'package:flower_app/features/profile/main_profile_screen/data/model/change_password_request_model.dart'
    as _i22;
import 'package:flower_app/features/profile/main_profile_screen/data/model/edit_profile_response_dto.dart'
    as _i23;
import 'package:flower_app/features/profile/main_profile_screen/data/model/profile_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponseDTO_0 extends _i1.SmartFake
    implements _i2.ProfileResponseDTO {
  _FakeProfileResponseDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDTO_1 extends _i1.SmartFake
    implements _i3.SignUpResponseDTO {
  _FakeSignUpResponseDTO_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpResponse_2<T> extends _i1.SmartFake
    implements _i4.HttpResponse<T> {
  _FakeHttpResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetResponsePasswordDto_3 extends _i1.SmartFake
    implements _i5.ForgetResponsePasswordDto {
  _FakeForgetResponsePasswordDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyEmailResponseDto_4 extends _i1.SmartFake
    implements _i6.VerifyEmailResponseDto {
  _FakeVerifyEmailResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDTO_5 extends _i1.SmartFake
    implements _i7.ResetPasswordResponseDTO {
  _FakeResetPasswordResponseDTO_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryResponseDTO_6 extends _i1.SmartFake
    implements _i8.CategoryResponseDTO {
  _FakeCategoryResponseDTO_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOccasionResponseDTO_7 extends _i1.SmartFake
    implements _i9.OccasionResponseDTO {
  _FakeOccasionResponseDTO_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOccasionsResponseDTO_8 extends _i1.SmartFake
    implements _i10.OccasionsResponseDTO {
  _FakeOccasionsResponseDTO_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductsResponseDTO_9 extends _i1.SmartFake
    implements _i11.ProductsResponseDTO {
  _FakeProductsResponseDTO_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoriesResponseModel_10 extends _i1.SmartFake
    implements _i12.CategoriesResponseModel {
  _FakeCategoriesResponseModel_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpecificCategoriesResponseModel_11 extends _i1.SmartFake
    implements _i13.SpecificCategoriesResponseModel {
  _FakeSpecificCategoriesResponseModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordModel_12 extends _i1.SmartFake
    implements _i14.ChangePasswordModel {
  _FakeChangePasswordModel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCartResponseModel_13 extends _i1.SmartFake
    implements _i15.UserCartResponseModel {
  _FakeUserCartResponseModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i16.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i2.ProfileResponseDTO> getProfileData(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [token],
        ),
        returnValue:
            _i17.Future<_i2.ProfileResponseDTO>.value(_FakeProfileResponseDTO_0(
          this,
          Invocation.method(
            #getProfileData,
            [token],
          ),
        )),
      ) as _i17.Future<_i2.ProfileResponseDTO>);

  @override
  _i17.Future<_i3.SignUpResponseDTO> signUp(_i18.SignUpRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [data],
        ),
        returnValue:
            _i17.Future<_i3.SignUpResponseDTO>.value(_FakeSignUpResponseDTO_1(
          this,
          Invocation.method(
            #signUp,
            [data],
          ),
        )),
      ) as _i17.Future<_i3.SignUpResponseDTO>);

  @override
  _i17.Future<_i4.HttpResponse<_i3.SignUpResponseDTO>> signIn(
          _i19.SignInRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [data],
        ),
        returnValue: _i17.Future<_i4.HttpResponse<_i3.SignUpResponseDTO>>.value(
            _FakeHttpResponse_2<_i3.SignUpResponseDTO>(
          this,
          Invocation.method(
            #signIn,
            [data],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i3.SignUpResponseDTO>>);

  @override
  _i17.Future<_i5.ForgetResponsePasswordDto> forgetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [data],
        ),
        returnValue: _i17.Future<_i5.ForgetResponsePasswordDto>.value(
            _FakeForgetResponsePasswordDto_3(
          this,
          Invocation.method(
            #forgetPassword,
            [data],
          ),
        )),
      ) as _i17.Future<_i5.ForgetResponsePasswordDto>);

  @override
  _i17.Future<_i6.VerifyEmailResponseDto> verifyEmail(
          Map<String, String>? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue: _i17.Future<_i6.VerifyEmailResponseDto>.value(
            _FakeVerifyEmailResponseDto_4(
          this,
          Invocation.method(
            #verifyEmail,
            [code],
          ),
        )),
      ) as _i17.Future<_i6.VerifyEmailResponseDto>);

  @override
  _i17.Future<_i7.ResetPasswordResponseDTO> resetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [data],
        ),
        returnValue: _i17.Future<_i7.ResetPasswordResponseDTO>.value(
            _FakeResetPasswordResponseDTO_5(
          this,
          Invocation.method(
            #resetPassword,
            [data],
          ),
        )),
      ) as _i17.Future<_i7.ResetPasswordResponseDTO>);

  @override
  _i17.Future<_i4.HttpResponse<_i20.BestSellerProductsModel>> getBestSeller() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBestSeller,
          [],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i20.BestSellerProductsModel>>.value(
                _FakeHttpResponse_2<_i20.BestSellerProductsModel>(
          this,
          Invocation.method(
            #getBestSeller,
            [],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i20.BestSellerProductsModel>>);

  @override
  _i17.Future<_i8.CategoryResponseDTO> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i17.Future<_i8.CategoryResponseDTO>.value(
            _FakeCategoryResponseDTO_6(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i17.Future<_i8.CategoryResponseDTO>);

  @override
  _i17.Future<_i9.OccasionResponseDTO> getOccasion() => (super.noSuchMethod(
        Invocation.method(
          #getOccasion,
          [],
        ),
        returnValue: _i17.Future<_i9.OccasionResponseDTO>.value(
            _FakeOccasionResponseDTO_7(
          this,
          Invocation.method(
            #getOccasion,
            [],
          ),
        )),
      ) as _i17.Future<_i9.OccasionResponseDTO>);

  @override
  _i17.Future<_i10.OccasionsResponseDTO> getOccasions() => (super.noSuchMethod(
        Invocation.method(
          #getOccasions,
          [],
        ),
        returnValue: _i17.Future<_i10.OccasionsResponseDTO>.value(
            _FakeOccasionsResponseDTO_8(
          this,
          Invocation.method(
            #getOccasions,
            [],
          ),
        )),
      ) as _i17.Future<_i10.OccasionsResponseDTO>);

  @override
  _i17.Future<_i11.ProductsResponseDTO> getProductsByOccasion(
          String? occasionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByOccasion,
          [occasionId],
        ),
        returnValue: _i17.Future<_i11.ProductsResponseDTO>.value(
            _FakeProductsResponseDTO_9(
          this,
          Invocation.method(
            #getProductsByOccasion,
            [occasionId],
          ),
        )),
      ) as _i17.Future<_i11.ProductsResponseDTO>);

  @override
  _i17.Future<_i4.HttpResponse<_i21.ProductsDetailsModels>> getProductDetails(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetails,
          [id],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i21.ProductsDetailsModels>>.value(
                _FakeHttpResponse_2<_i21.ProductsDetailsModels>(
          this,
          Invocation.method(
            #getProductDetails,
            [id],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i21.ProductsDetailsModels>>);

  @override
  _i17.Future<_i12.CategoriesResponseModel> getAllCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i17.Future<_i12.CategoriesResponseModel>.value(
            _FakeCategoriesResponseModel_10(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i17.Future<_i12.CategoriesResponseModel>);

  @override
  _i17.Future<_i13.SpecificCategoriesResponseModel> getSpecificCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificCategory,
          [categoryId],
        ),
        returnValue: _i17.Future<_i13.SpecificCategoriesResponseModel>.value(
            _FakeSpecificCategoriesResponseModel_11(
          this,
          Invocation.method(
            #getSpecificCategory,
            [categoryId],
          ),
        )),
      ) as _i17.Future<_i13.SpecificCategoriesResponseModel>);

  @override
  _i17.Future<_i4.HttpResponse<void>> logout(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<void>>.value(_FakeHttpResponse_2<void>(
          this,
          Invocation.method(
            #logout,
            [token],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<void>>);

  @override
  _i17.Future<_i14.ChangePasswordModel> changePassword(
    _i22.ChangePasswordRequestModel? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            data,
            token,
          ],
        ),
        returnValue: _i17.Future<_i14.ChangePasswordModel>.value(
            _FakeChangePasswordModel_12(
          this,
          Invocation.method(
            #changePassword,
            [
              data,
              token,
            ],
          ),
        )),
      ) as _i17.Future<_i14.ChangePasswordModel>);

  @override
  _i17.Future<_i4.HttpResponse<_i23.EditProfileResponseDTO>> editProfile(
    String? token,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [
            token,
            data,
          ],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i23.EditProfileResponseDTO>>.value(
                _FakeHttpResponse_2<_i23.EditProfileResponseDTO>(
          this,
          Invocation.method(
            #editProfile,
            [
              token,
              data,
            ],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i23.EditProfileResponseDTO>>);

  @override
  _i17.Future<String?> uploadPhoto(
    String? token,
    _i24.FormData? formData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [
            token,
            formData,
          ],
        ),
        returnValue: _i17.Future<String?>.value(),
      ) as _i17.Future<String?>);

  @override
  _i17.Future<_i4.HttpResponse<_i25.CreateCartResponse>> addProductToCart(
    String? token,
    _i26.CreateCartRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductToCart,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i25.CreateCartResponse>>.value(
                _FakeHttpResponse_2<_i25.CreateCartResponse>(
          this,
          Invocation.method(
            #addProductToCart,
            [
              token,
              request,
            ],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i25.CreateCartResponse>>);

  @override
  _i17.Future<_i15.UserCartResponseModel> getUserCart(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCart,
          [token],
        ),
        returnValue: _i17.Future<_i15.UserCartResponseModel>.value(
            _FakeUserCartResponseModel_13(
          this,
          Invocation.method(
            #getUserCart,
            [token],
          ),
        )),
      ) as _i17.Future<_i15.UserCartResponseModel>);

  @override
  _i17.Future<_i4.HttpResponse<_i27.DeleteCartResponseDTO>> deleteCartItem(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCartItem,
          [
            token,
            id,
          ],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i27.DeleteCartResponseDTO>>.value(
                _FakeHttpResponse_2<_i27.DeleteCartResponseDTO>(
          this,
          Invocation.method(
            #deleteCartItem,
            [
              token,
              id,
            ],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i27.DeleteCartResponseDTO>>);

  @override
  _i17.Future<
      _i4.HttpResponse<_i28.UpdateCartQuantityResponseDTO>> updateCartQuantity(
    String? token,
    String? id,
    _i29.UpdateCartQuantityRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartQuantity,
          [
            token,
            id,
            request,
          ],
        ),
        returnValue: _i17
            .Future<_i4.HttpResponse<_i28.UpdateCartQuantityResponseDTO>>.value(
            _FakeHttpResponse_2<_i28.UpdateCartQuantityResponseDTO>(
          this,
          Invocation.method(
            #updateCartQuantity,
            [
              token,
              id,
              request,
            ],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i28.UpdateCartQuantityResponseDTO>>);

  @override
  _i17.Future<_i4.HttpResponse<_i30.AddressesResponseDTO>> getAddresses(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddresses,
          [token],
        ),
        returnValue:
            _i17.Future<_i4.HttpResponse<_i30.AddressesResponseDTO>>.value(
                _FakeHttpResponse_2<_i30.AddressesResponseDTO>(
          this,
          Invocation.method(
            #getAddresses,
            [token],
          ),
        )),
      ) as _i17.Future<_i4.HttpResponse<_i30.AddressesResponseDTO>>);
}
