// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/data/data_source/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/core/api/api_client.dart' as _i4;
import 'package:flower_app/auth/data/model/sign_up_response_dto.dart'
    as _i2;
import 'package:flower_app/auth/domain/entity/sign_in_request.dart' as _i7;
import 'package:flower_app/auth/domain/entity/sign_up_request.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseDTO_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDTO {
  _FakeSignUpResponseDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SignUpResponseDTO> signUp(_i6.SignUpRequest? data) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [data]),
            returnValue: _i5.Future<_i2.SignUpResponseDTO>.value(
              _FakeSignUpResponseDTO_0(
                this,
                Invocation.method(#signUp, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDTO>);

  @override
  _i5.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>> signIn(
    _i7.SignInRequest? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [data]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>.value(
                  _FakeHttpResponse_1<_i2.SignUpResponseDTO>(
                    this,
                    Invocation.method(#signIn, [data]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>);
}
