// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/home/occasions/data/repository_imp/occasion_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/home/occasions/data/data_source/occasion_remote_data_source.dart'
    as _i4;
import 'package:flower_app/features/home/occasions/data/model/occasions_dto.dart'
    as _i2;
import 'package:flower_app/features/home/occasions/data/model/products_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOccasionsResponseDTO_0 extends _i1.SmartFake
    implements _i2.OccasionsResponseDTO {
  _FakeOccasionsResponseDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponseDTO_1 extends _i1.SmartFake
    implements _i3.ProductsResponseDTO {
  _FakeProductsResponseDTO_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OccasionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccasionRemoteDataSource extends _i1.Mock
    implements _i4.OccasionRemoteDataSource {
  MockOccasionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OccasionsResponseDTO> getOccasion() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasion, []),
            returnValue: _i5.Future<_i2.OccasionsResponseDTO>.value(
              _FakeOccasionsResponseDTO_0(
                this,
                Invocation.method(#getOccasion, []),
              ),
            ),
          )
          as _i5.Future<_i2.OccasionsResponseDTO>);

  @override
  _i5.Future<_i3.ProductsResponseDTO> getOccasionDetails(String? occasionId) =>
      (super.noSuchMethod(
            Invocation.method(#getOccasionDetails, [occasionId]),
            returnValue: _i5.Future<_i3.ProductsResponseDTO>.value(
              _FakeProductsResponseDTO_1(
                this,
                Invocation.method(#getOccasionDetails, [occasionId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductsResponseDTO>);
}
