// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFAFRcPnfsS3E4_FhlD21xpB_cZNJDu8',
    appId: '1:916571065039:web:2524d86dcceb47152f05ba',
    messagingSenderId: '916571065039',
    projectId: 'flower-app-8039c',
    authDomain: 'flower-app-8039c.firebaseapp.com',
    storageBucket: 'flower-app-8039c.firebasestorage.app',
    measurementId: 'G-BCE15VVV0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqR3OUgKgzA3RaWtMQoDGO9yseQbli26Y',
    appId: '1:916571065039:android:b509251e054411282f05ba',
    messagingSenderId: '916571065039',
    projectId: 'flower-app-8039c',
    storageBucket: 'flower-app-8039c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1e2LokCCeT885ZTzSM-bayM9u5DOM-RY',
    appId: '1:916571065039:ios:fdf442da2c474a1d2f05ba',
    messagingSenderId: '916571065039',
    projectId: 'flower-app-8039c',
    storageBucket: 'flower-app-8039c.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1e2LokCCeT885ZTzSM-bayM9u5DOM-RY',
    appId: '1:916571065039:ios:fdf442da2c474a1d2f05ba',
    messagingSenderId: '916571065039',
    projectId: 'flower-app-8039c',
    storageBucket: 'flower-app-8039c.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaFAFRcPnfsS3E4_FhlD21xpB_cZNJDu8',
    appId: '1:916571065039:web:7da679a7f3c492a82f05ba',
    messagingSenderId: '916571065039',
    projectId: 'flower-app-8039c',
    authDomain: 'flower-app-8039c.firebaseapp.com',
    storageBucket: 'flower-app-8039c.firebasestorage.app',
    measurementId: 'G-1Y1M54DRZ0',
  );
}
