class StateEntity {
  final String id;
  final String governorateId;
  final String cityNameAr;
  final String cityNameEn;

  StateEntity({
    required this.id,
    required this.governorateId,
    required this.cityNameAr,
    required this.cityNameEn,
  });
}

List<StateEntity> states = [
  StateEntity(
    id: "1",
    governorateId: "1",
    cityNameAr: "15 مايو",
    cityNameEn: "15 May",
  ),
  StateEntity(
    id: "2",
    governorateId: "1",
    cityNameAr: "الازبكية",
    cityNameEn: "Al Azbakeyah",
  ),
  StateEntity(
    id: "3",
    governorateId: "1",
    cityNameAr: "البساتين",
    cityNameEn: "Al Basatin",
  ),
  StateEntity(
    id: "4",
    governorateId: "1",
    cityNameAr: "التبين",
    cityNameEn: "Tebin",
  ),
  StateEntity(
    id: "5",
    governorateId: "1",
    cityNameAr: "الخليفة",
    cityNameEn: "El-Khalifa",
  ),
  StateEntity(
    id: "6",
    governorateId: "1",
    cityNameAr: "الدراسة",
    cityNameEn: "El darrasa",
  ),
  StateEntity(
    id: "7",
    governorateId: "1",
    cityNameAr: "الدرب الاحمر",
    cityNameEn: "Aldarb Alahmar",
  ),
  StateEntity(
    id: "8",
    governorateId: "1",
    cityNameAr: "الزاوية الحمراء",
    cityNameEn: "Zawya al-Hamra",
  ),
  StateEntity(
    id: "9",
    governorateId: "1",
    cityNameAr: "الزيتون",
    cityNameEn: "El-Zaytoun",
  ),
  StateEntity(
    id: "10",
    governorateId: "1",
    cityNameAr: "الساحل",
    cityNameEn: "Sahel",
  ),
  StateEntity(
    id: "11",
    governorateId: "1",
    cityNameAr: "السلام",
    cityNameEn: "El Salam",
  ),
  StateEntity(
    id: "12",
    governorateId: "1",
    cityNameAr: "السيدة زينب",
    cityNameEn: "Sayeda Zeinab",
  ),
  StateEntity(
    id: "13",
    governorateId: "1",
    cityNameAr: "الشرابية",
    cityNameEn: "El Sharabeya",
  ),
  StateEntity(
    id: "14",
    governorateId: "1",
    cityNameAr: "مدينة الشروق",
    cityNameEn: "Shorouk",
  ),
  StateEntity(
    id: "15",
    governorateId: "1",
    cityNameAr: "الظاهر",
    cityNameEn: "El Daher",
  ),
  StateEntity(
    id: "16",
    governorateId: "1",
    cityNameAr: "العتبة",
    cityNameEn: "Ataba",
  ),
  StateEntity(
    id: "17",
    governorateId: "1",
    cityNameAr: "القاهرة الجديدة",
    cityNameEn: "New Cairo",
  ),
  StateEntity(
    id: "18",
    governorateId: "1",
    cityNameAr: "المرج",
    cityNameEn: "El Marg",
  ),
  StateEntity(
    id: "19",
    governorateId: "1",
    cityNameAr: "عزبة النخل",
    cityNameEn: "Ezbet el Nakhl",
  ),
  StateEntity(
    id: "20",
    governorateId: "1",
    cityNameAr: "المطرية",
    cityNameEn: "Matareya",
  ),
  StateEntity(
    id: "21",
    governorateId: "1",
    cityNameAr: "المعادى",
    cityNameEn: "Maadi",
  ),
  StateEntity(
    id: "22",
    governorateId: "1",
    cityNameAr: "المعصرة",
    cityNameEn: "Maasara",
  ),
  StateEntity(
    id: "23",
    governorateId: "1",
    cityNameAr: "المقطم",
    cityNameEn: "Mokattam",
  ),
  StateEntity(
    id: "24",
    governorateId: "1",
    cityNameAr: "المنيل",
    cityNameEn: "Manyal",
  ),
  StateEntity(
    id: "25",
    governorateId: "1",
    cityNameAr: "الموسكى",
    cityNameEn: "Mosky",
  ),
  StateEntity(
    id: "26",
    governorateId: "1",
    cityNameAr: "النزهة",
    cityNameEn: "Nozha",
  ),
  StateEntity(
    id: "27",
    governorateId: "1",
    cityNameAr: "الوايلى",
    cityNameEn: "Waily",
  ),
  StateEntity(
    id: "28",
    governorateId: "1",
    cityNameAr: "باب الشعرية",
    cityNameEn: "Bab al-Shereia",
  ),
  StateEntity(
    id: "29",
    governorateId: "1",
    cityNameAr: "بولاق",
    cityNameEn: "Bolaq",
  ),
  StateEntity(
    id: "30",
    governorateId: "1",
    cityNameAr: "جاردن سيتى",
    cityNameEn: "Garden City",
  ),
  StateEntity(
    id: "31",
    governorateId: "1",
    cityNameAr: "حدائق القبة",
    cityNameEn: "Hadayek El-Kobba",
  ),
  StateEntity(
    id: "32",
    governorateId: "1",
    cityNameAr: "حلوان",
    cityNameEn: "Helwan",
  ),
  StateEntity(
    id: "33",
    governorateId: "1",
    cityNameAr: "دار السلام",
    cityNameEn: "Dar Al Salam",
  ),
  StateEntity(
    id: "34",
    governorateId: "1",
    cityNameAr: "شبرا",
    cityNameEn: "Shubra",
  ),
  StateEntity(
    id: "35",
    governorateId: "1",
    cityNameAr: "طره",
    cityNameEn: "Tura",
  ),
  StateEntity(
    id: "36",
    governorateId: "1",
    cityNameAr: "عابدين",
    cityNameEn: "Abdeen",
  ),
  StateEntity(
    id: "37",
    governorateId: "1",
    cityNameAr: "عباسية",
    cityNameEn: "Abaseya",
  ),
  StateEntity(
    id: "38",
    governorateId: "1",
    cityNameAr: "عين شمس",
    cityNameEn: "Ain Shams",
  ),
  StateEntity(
    id: "39",
    governorateId: "1",
    cityNameAr: "مدينة نصر",
    cityNameEn: "Nasr City",
  ),
  StateEntity(
    id: "40",
    governorateId: "1",
    cityNameAr: "مصر الجديدة",
    cityNameEn: "New Heliopolis",
  ),
  StateEntity(
    id: "41",
    governorateId: "1",
    cityNameAr: "مصر القديمة",
    cityNameEn: "Masr Al Qadima",
  ),
  StateEntity(
    id: "42",
    governorateId: "1",
    cityNameAr: "منشية ناصر",
    cityNameEn: "Mansheya Nasir",
  ),
  StateEntity(
    id: "43",
    governorateId: "1",
    cityNameAr: "مدينة بدر",
    cityNameEn: "Badr City",
  ),
  StateEntity(
    id: "44",
    governorateId: "1",
    cityNameAr: "مدينة العبور",
    cityNameEn: "Obour City",
  ),
  StateEntity(
    id: "45",
    governorateId: "1",
    cityNameAr: "وسط البلد",
    cityNameEn: "Cairo Downtown",
  ),
  StateEntity(
    id: "46",
    governorateId: "1",
    cityNameAr: "الزمالك",
    cityNameEn: "Zamalek",
  ),
  StateEntity(
    id: "47",
    governorateId: "1",
    cityNameAr: "قصر النيل",
    cityNameEn: "Kasr El Nile",
  ),
  StateEntity(
    id: "48",
    governorateId: "1",
    cityNameAr: "الرحاب",
    cityNameEn: "Rehab",
  ),
  StateEntity(
    id: "49",
    governorateId: "1",
    cityNameAr: "القطامية",
    cityNameEn: "Katameya",
  ),
  StateEntity(
    id: "50",
    governorateId: "1",
    cityNameAr: "مدينتي",
    cityNameEn: "Madinty",
  ),
  StateEntity(
    id: "51",
    governorateId: "1",
    cityNameAr: "روض الفرج",
    cityNameEn: "Rod Alfarag",
  ),
  StateEntity(
    id: "52",
    governorateId: "1",
    cityNameAr: "شيراتون",
    cityNameEn: "Sheraton",
  ),
  StateEntity(
    id: "53",
    governorateId: "1",
    cityNameAr: "الجمالية",
    cityNameEn: "El-Gamaleya",
  ),
  StateEntity(
    id: "54",
    governorateId: "1",
    cityNameAr: "العاشر من رمضان",
    cityNameEn: "10th of Ramadan City",
  ),
  StateEntity(
    id: "55",
    governorateId: "1",
    cityNameAr: "الحلمية",
    cityNameEn: "Helmeyat Alzaytoun",
  ),
  StateEntity(
    id: "56",
    governorateId: "1",
    cityNameAr: "النزهة الجديدة",
    cityNameEn: "New Nozha",
  ),
  StateEntity(
    id: "57",
    governorateId: "1",
    cityNameAr: "العاصمة الإدارية",
    cityNameEn: "Capital New",
  ),
  StateEntity(
    id: "58",
    governorateId: "2",
    cityNameAr: "الجيزة",
    cityNameEn: "Giza",
  ),
  StateEntity(
    id: "59",
    governorateId: "2",
    cityNameAr: "السادس من أكتوبر",
    cityNameEn: "Sixth of October",
  ),
  StateEntity(
    id: "60",
    governorateId: "2",
    cityNameAr: "الشيخ زايد",
    cityNameEn: "Cheikh Zayed",
  ),
  StateEntity(
    id: "61",
    governorateId: "2",
    cityNameAr: "الحوامدية",
    cityNameEn: "Hawamdiyah",
  ),
  StateEntity(
    id: "62",
    governorateId: "2",
    cityNameAr: "البدرشين",
    cityNameEn: "Al Badrasheen",
  ),
  StateEntity(
    id: "63",
    governorateId: "2",
    cityNameAr: "الصف",
    cityNameEn: "Saf",
  ),
  StateEntity(
    id: "64",
    governorateId: "2",
    cityNameAr: "أطفيح",
    cityNameEn: "Atfih",
  ),
  StateEntity(
    id: "65",
    governorateId: "2",
    cityNameAr: "العياط",
    cityNameEn: "Al Ayat",
  ),
  StateEntity(
    id: "66",
    governorateId: "2",
    cityNameAr: "الباويطي",
    cityNameEn: "Al-Bawaiti",
  ),
  StateEntity(
    id: "67",
    governorateId: "2",
    cityNameAr: "منشأة القناطر",
    cityNameEn: "ManshiyetAl Qanater",
  ),
  StateEntity(
    id: "68",
    governorateId: "2",
    cityNameAr: "أوسيم",
    cityNameEn: "Oaseem",
  ),
  StateEntity(
    id: "69",
    governorateId: "2",
    cityNameAr: "كرداسة",
    cityNameEn: "Kerdasa",
  ),
  StateEntity(
    id: "70",
    governorateId: "2",
    cityNameAr: "أبو النمرس",
    cityNameEn: "Abu Nomros",
  ),
  StateEntity(
    id: "71",
    governorateId: "2",
    cityNameAr: "كفر غطاطي",
    cityNameEn: "Kafr Ghati",
  ),
  StateEntity(
    id: "72",
    governorateId: "2",
    cityNameAr: "منشأة البكاري",
    cityNameEn: "Manshiyet Al Bakari",
  ),
  StateEntity(
    id: "73",
    governorateId: "2",
    cityNameAr: "الدقى",
    cityNameEn: "Dokki",
  ),
  StateEntity(
    id: "74",
    governorateId: "2",
    cityNameAr: "العجوزة",
    cityNameEn: "Agouza",
  ),
  StateEntity(
    id: "75",
    governorateId: "2",
    cityNameAr: "الهرم",
    cityNameEn: "Haram",
  ),
  StateEntity(
    id: "76",
    governorateId: "2",
    cityNameAr: "الوراق",
    cityNameEn: "Warraq",
  ),
  StateEntity(
    id: "77",
    governorateId: "2",
    cityNameAr: "امبابة",
    cityNameEn: "Imbaba",
  ),
  StateEntity(
    id: "78",
    governorateId: "2",
    cityNameAr: "بولاق الدكرور",
    cityNameEn: "Boulaq Dakrour",
  ),
  StateEntity(
    id: "79",
    governorateId: "2",
    cityNameAr: "الواحات البحرية",
    cityNameEn: "Al Wahat Al Baharia",
  ),
  StateEntity(
    id: "80",
    governorateId: "2",
    cityNameAr: "العمرانية",
    cityNameEn: "Omraneya",
  ),
  StateEntity(
    id: "81",
    governorateId: "2",
    cityNameAr: "المنيب",
    cityNameEn: "Moneeb",
  ),
  StateEntity(
    id: "82",
    governorateId: "2",
    cityNameAr: "بين السرايات",
    cityNameEn: "Bin Alsarayat",
  ),
  StateEntity(
    id: "83",
    governorateId: "2",
    cityNameAr: "الكيت كات",
    cityNameEn: "Kit Kat",
  ),
  StateEntity(
    id: "84",
    governorateId: "2",
    cityNameAr: "المهندسين",
    cityNameEn: "Mohandessin",
  ),
  StateEntity(
    id: "85",
    governorateId: "2",
    cityNameAr: "فيصل",
    cityNameEn: "Faisal",
  ),
  StateEntity(
    id: "86",
    governorateId: "2",
    cityNameAr: "أبو رواش",
    cityNameEn: "Abu Rawash",
  ),
  StateEntity(
    id: "87",
    governorateId: "2",
    cityNameAr: "حدائق الأهرام",
    cityNameEn: "Hadayek Alahram",
  ),
  StateEntity(
    id: "88",
    governorateId: "2",
    cityNameAr: "الحرانية",
    cityNameEn: "Haraneya",
  ),
  StateEntity(
    id: "89",
    governorateId: "2",
    cityNameAr: "حدائق اكتوبر",
    cityNameEn: "Hadayek October",
  ),
  StateEntity(
    id: "90",
    governorateId: "2",
    cityNameAr: "صفط اللبن",
    cityNameEn: "Saft Allaban",
  ),
  StateEntity(
    id: "91",
    governorateId: "2",
    cityNameAr: "القرية الذكية",
    cityNameEn: "Smart Village",
  ),
  StateEntity(
    id: "92",
    governorateId: "2",
    cityNameAr: "ارض اللواء",
    cityNameEn: "Ard Ellwaa",
  ),
  StateEntity(
    id: "93",
    governorateId: "3",
    cityNameAr: "ابو قير",
    cityNameEn: "Abu Qir",
  ),
  StateEntity(
    id: "94",
    governorateId: "3",
    cityNameAr: "الابراهيمية",
    cityNameEn: "Al Ibrahimeyah",
  ),
  StateEntity(
    id: "95",
    governorateId: "3",
    cityNameAr: "الأزاريطة",
    cityNameEn: "Azarita",
  ),
  StateEntity(
    id: "96",
    governorateId: "3",
    cityNameAr: "الانفوشى",
    cityNameEn: "Anfoushi",
  ),
  StateEntity(
    id: "97",
    governorateId: "3",
    cityNameAr: "الدخيلة",
    cityNameEn: "Dekheila",
  ),
  StateEntity(
    id: "98",
    governorateId: "3",
    cityNameAr: "السيوف",
    cityNameEn: "El Soyof",
  ),
  StateEntity(
    id: "99",
    governorateId: "3",
    cityNameAr: "العامرية",
    cityNameEn: "Ameria",
  ),
  StateEntity(
    id: "100",
    governorateId: "3",
    cityNameAr: "اللبان",
    cityNameEn: "El Labban",
  ),
  StateEntity(
    id: "101",
    governorateId: "3",
    cityNameAr: "المفروزة",
    cityNameEn: "Al Mafrouza",
  ),
  StateEntity(
    id: "102",
    governorateId: "3",
    cityNameAr: "المنتزه",
    cityNameEn: "El Montaza",
  ),
  StateEntity(
    id: "103",
    governorateId: "3",
    cityNameAr: "المنشية",
    cityNameEn: "Mansheya",
  ),
  StateEntity(
    id: "104",
    governorateId: "3",
    cityNameAr: "الناصرية",
    cityNameEn: "Naseria",
  ),
  StateEntity(
    id: "105",
    governorateId: "3",
    cityNameAr: "امبروزو",
    cityNameEn: "Ambrozo",
  ),
  StateEntity(
    id: "106",
    governorateId: "3",
    cityNameAr: "باب شرق",
    cityNameEn: "Bab Sharq",
  ),
  StateEntity(
    id: "107",
    governorateId: "3",
    cityNameAr: "برج العرب",
    cityNameEn: "Bourj Alarab",
  ),
  StateEntity(
    id: "108",
    governorateId: "3",
    cityNameAr: "ستانلى",
    cityNameEn: "Stanley",
  ),
  StateEntity(
    id: "109",
    governorateId: "3",
    cityNameAr: "سموحة",
    cityNameEn: "Smouha",
  ),
  StateEntity(
    id: "110",
    governorateId: "3",
    cityNameAr: "سيدى بشر",
    cityNameEn: "Sidi Bishr",
  ),
  StateEntity(
    id: "111",
    governorateId: "3",
    cityNameAr: "شدس",
    cityNameEn: "Shads",
  ),
  StateEntity(
    id: "112",
    governorateId: "3",
    cityNameAr: "غيط العنب",
    cityNameEn: "Gheet Alenab",
  ),
  StateEntity(
    id: "113",
    governorateId: "3",
    cityNameAr: "فلمينج",
    cityNameEn: "Fleming",
  ),
  StateEntity(
    id: "114",
    governorateId: "3",
    cityNameAr: "فيكتوريا",
    cityNameEn: "Victoria",
  ),
  StateEntity(
    id: "115",
    governorateId: "3",
    cityNameAr: "كامب شيزار",
    cityNameEn: "Camp Shizar",
  ),
  StateEntity(
    id: "116",
    governorateId: "3",
    cityNameAr: "كرموز",
    cityNameEn: "Karmooz",
  ),
  StateEntity(
    id: "117",
    governorateId: "3",
    cityNameAr: "محطة الرمل",
    cityNameEn: "Mahta Alraml",
  ),
  StateEntity(
    id: "118",
    governorateId: "3",
    cityNameAr: "مينا البصل",
    cityNameEn: "Mina El-Basal",
  ),
  StateEntity(
    id: "119",
    governorateId: "3",
    cityNameAr: "العصافرة",
    cityNameEn: "Asafra",
  ),
  StateEntity(
    id: "120",
    governorateId: "3",
    cityNameAr: "العجمي",
    cityNameEn: "Agamy",
  ),
  StateEntity(
    id: "121",
    governorateId: "3",
    cityNameAr: "بكوس",
    cityNameEn: "Bakos",
  ),
  StateEntity(
    id: "122",
    governorateId: "3",
    cityNameAr: "بولكلي",
    cityNameEn: "Boulkly",
  ),
  StateEntity(
    id: "123",
    governorateId: "3",
    cityNameAr: "كليوباترا",
    cityNameEn: "Cleopatra",
  ),
  StateEntity(
    id: "124",
    governorateId: "3",
    cityNameAr: "جليم",
    cityNameEn: "Glim",
  ),
  StateEntity(
    id: "125",
    governorateId: "3",
    cityNameAr: "المعمورة",
    cityNameEn: "Al Mamurah",
  ),
  StateEntity(
    id: "126",
    governorateId: "3",
    cityNameAr: "المندرة",
    cityNameEn: "Al Mandara",
  ),
  StateEntity(
    id: "127",
    governorateId: "3",
    cityNameAr: "محرم بك",
    cityNameEn: "Moharam Bek",
  ),
  StateEntity(
    id: "128",
    governorateId: "3",
    cityNameAr: "الشاطبي",
    cityNameEn: "Elshatby",
  ),
  StateEntity(
    id: "129",
    governorateId: "3",
    cityNameAr: "سيدي جابر",
    cityNameEn: "Sidi Gaber",
  ),
  StateEntity(
    id: "130",
    governorateId: "3",
    cityNameAr: "الساحل الشمالي",
    cityNameEn: "North Coast/sahel",
  ),
  StateEntity(
    id: "131",
    governorateId: "3",
    cityNameAr: "الحضرة",
    cityNameEn: "Alhadra",
  ),
  StateEntity(
    id: "132",
    governorateId: "3",
    cityNameAr: "العطارين",
    cityNameEn: "Alattarin",
  ),
  StateEntity(
    id: "133",
    governorateId: "3",
    cityNameAr: "سيدي كرير",
    cityNameEn: "Sidi Kerir",
  ),
  StateEntity(
    id: "134",
    governorateId: "3",
    cityNameAr: "الجمرك",
    cityNameEn: "Elgomrok",
  ),
  StateEntity(
    id: "135",
    governorateId: "3",
    cityNameAr: "المكس",
    cityNameEn: "Al Max",
  ),
  StateEntity(
    id: "136",
    governorateId: "3",
    cityNameAr: "مارينا",
    cityNameEn: "Marina",
  ),
  StateEntity(
    id: "137",
    governorateId: "4",
    cityNameAr: "المنصورة",
    cityNameEn: "Mansoura",
  ),
  StateEntity(
    id: "138",
    governorateId: "4",
    cityNameAr: "طلخا",
    cityNameEn: "Talkha",
  ),
  StateEntity(
    id: "139",
    governorateId: "4",
    cityNameAr: "ميت غمر",
    cityNameEn: "Mitt Ghamr",
  ),
  StateEntity(
    id: "140",
    governorateId: "4",
    cityNameAr: "دكرنس",
    cityNameEn: "Dekernes",
  ),
  StateEntity(
    id: "141",
    governorateId: "4",
    cityNameAr: "أجا",
    cityNameEn: "Aga",
  ),
  StateEntity(
    id: "142",
    governorateId: "4",
    cityNameAr: "منية النصر",
    cityNameEn: "Menia El Nasr",
  ),
  StateEntity(
    id: "143",
    governorateId: "4",
    cityNameAr: "السنبلاوين",
    cityNameEn: "Sinbillawin",
  ),
  StateEntity(
    id: "144",
    governorateId: "4",
    cityNameAr: "الكردي",
    cityNameEn: "El Kurdi",
  ),
  StateEntity(
    id: "145",
    governorateId: "4",
    cityNameAr: "بني عبيد",
    cityNameEn: "Bani Ubaid",
  ),
  StateEntity(
    id: "146",
    governorateId: "4",
    cityNameAr: "المنزلة",
    cityNameEn: "Al Manzala",
  ),
  StateEntity(
    id: "147",
    governorateId: "4",
    cityNameAr: "تمي الأمديد",
    cityNameEn: "tami al'amdid",
  ),
  StateEntity(
    id: "148",
    governorateId: "4",
    cityNameAr: "الجمالية",
    cityNameEn: "aljamalia",
  ),
  StateEntity(
    id: "149",
    governorateId: "4",
    cityNameAr: "شربين",
    cityNameEn: "Sherbin",
  ),
  StateEntity(
    id: "150",
    governorateId: "4",
    cityNameAr: "المطرية",
    cityNameEn: "Mataria",
  ),
  StateEntity(
    id: "151",
    governorateId: "4",
    cityNameAr: "بلقاس",
    cityNameEn: "Belqas",
  ),
  StateEntity(
    id: "152",
    governorateId: "4",
    cityNameAr: "ميت سلسيل",
    cityNameEn: "Meet Salsil",
  ),
  StateEntity(
    id: "153",
    governorateId: "4",
    cityNameAr: "جمصة",
    cityNameEn: "Gamasa",
  ),
  StateEntity(
    id: "154",
    governorateId: "4",
    cityNameAr: "محلة دمنة",
    cityNameEn: "Mahalat Damana",
  ),
  StateEntity(
    id: "155",
    governorateId: "4",
    cityNameAr: "نبروه",
    cityNameEn: "Nabroh",
  ),
  StateEntity(
    id: "156",
    governorateId: "5",
    cityNameAr: "الغردقة",
    cityNameEn: "Hurghada",
  ),
  StateEntity(
    id: "157",
    governorateId: "5",
    cityNameAr: "رأس غارب",
    cityNameEn: "Ras Ghareb",
  ),
  StateEntity(
    id: "158",
    governorateId: "5",
    cityNameAr: "سفاجا",
    cityNameEn: "Safaga",
  ),
  StateEntity(
    id: "159",
    governorateId: "5",
    cityNameAr: "القصير",
    cityNameEn: "El Qusiar",
  ),
  StateEntity(
    id: "160",
    governorateId: "5",
    cityNameAr: "مرسى علم",
    cityNameEn: "Marsa Alam",
  ),
  StateEntity(
    id: "161",
    governorateId: "5",
    cityNameAr: "الشلاتين",
    cityNameEn: "Shalatin",
  ),
  StateEntity(
    id: "162",
    governorateId: "5",
    cityNameAr: "حلايب",
    cityNameEn: "Halaib",
  ),
  StateEntity(
    id: "163",
    governorateId: "5",
    cityNameAr: "الدهار",
    cityNameEn: "Aldahar",
  ),
  StateEntity(
    id: "164",
    governorateId: "6",
    cityNameAr: "دمنهور",
    cityNameEn: "Damanhour",
  ),
  StateEntity(
    id: "165",
    governorateId: "6",
    cityNameAr: "كفر الدوار",
    cityNameEn: "Kafr El Dawar",
  ),
  StateEntity(
    id: "166",
    governorateId: "6",
    cityNameAr: "رشيد",
    cityNameEn: "Rashid",
  ),
  StateEntity(
    id: "167",
    governorateId: "6",
    cityNameAr: "إدكو",
    cityNameEn: "Edco",
  ),
  StateEntity(
    id: "168",
    governorateId: "6",
    cityNameAr: "أبو المطامير",
    cityNameEn: "Abu al-Matamir",
  ),
  StateEntity(
    id: "169",
    governorateId: "6",
    cityNameAr: "أبو حمص",
    cityNameEn: "Abu Homs",
  ),
  StateEntity(
    id: "170",
    governorateId: "6",
    cityNameAr: "الدلنجات",
    cityNameEn: "Delengat",
  ),
  StateEntity(
    id: "171",
    governorateId: "6",
    cityNameAr: "المحمودية",
    cityNameEn: "Mahmoudiyah",
  ),
  StateEntity(
    id: "172",
    governorateId: "6",
    cityNameAr: "الرحمانية",
    cityNameEn: "Rahmaniyah",
  ),
  StateEntity(
    id: "173",
    governorateId: "6",
    cityNameAr: "إيتاي البارود",
    cityNameEn: "Itai Baroud",
  ),
  StateEntity(
    id: "174",
    governorateId: "6",
    cityNameAr: "حوش عيسى",
    cityNameEn: "Housh Eissa",
  ),
  StateEntity(
    id: "175",
    governorateId: "6",
    cityNameAr: "شبراخيت",
    cityNameEn: "Shubrakhit",
  ),
  StateEntity(
    id: "176",
    governorateId: "6",
    cityNameAr: "كوم حمادة",
    cityNameEn: "Kom Hamada",
  ),
  StateEntity(
    id: "177",
    governorateId: "6",
    cityNameAr: "بدر",
    cityNameEn: "Badr",
  ),
  StateEntity(
    id: "178",
    governorateId: "6",
    cityNameAr: "وادي النطرون",
    cityNameEn: "Wadi Natrun",
  ),
  StateEntity(
    id: "179",
    governorateId: "6",
    cityNameAr: "النوبارية الجديدة",
    cityNameEn: "New Nubaria",
  ),
  StateEntity(
    id: "180",
    governorateId: "6",
    cityNameAr: "النوبارية",
    cityNameEn: "Alnoubareya",
  ),
  StateEntity(
    id: "181",
    governorateId: "7",
    cityNameAr: "الفيوم",
    cityNameEn: "Fayoum",
  ),
  StateEntity(
    id: "182",
    governorateId: "7",
    cityNameAr: "الفيوم الجديدة",
    cityNameEn: "Fayoum El Gedida",
  ),
  StateEntity(
    id: "183",
    governorateId: "7",
    cityNameAr: "طامية",
    cityNameEn: "Tamiya",
  ),
  StateEntity(
    id: "184",
    governorateId: "7",
    cityNameAr: "سنورس",
    cityNameEn: "Snores",
  ),
  StateEntity(
    id: "185",
    governorateId: "7",
    cityNameAr: "إطسا",
    cityNameEn: "Etsa",
  ),
  StateEntity(
    id: "186",
    governorateId: "7",
    cityNameAr: "إبشواي",
    cityNameEn: "Epschway",
  ),
  StateEntity(
    id: "187",
    governorateId: "7",
    cityNameAr: "يوسف الصديق",
    cityNameEn: "Yusuf El Sediaq",
  ),
  StateEntity(
    id: "188",
    governorateId: "7",
    cityNameAr: "الحادقة",
    cityNameEn: "Hadqa",
  ),
  StateEntity(
    id: "189",
    governorateId: "7",
    cityNameAr: "اطسا",
    cityNameEn: "Atsa",
  ),
  StateEntity(
    id: "190",
    governorateId: "7",
    cityNameAr: "الجامعة",
    cityNameEn: "Algamaa",
  ),
  StateEntity(
    id: "191",
    governorateId: "7",
    cityNameAr: "السيالة",
    cityNameEn: "Sayala",
  ),
  StateEntity(
    id: "192",
    governorateId: "8",
    cityNameAr: "طنطا",
    cityNameEn: "Tanta",
  ),
  StateEntity(
    id: "193",
    governorateId: "8",
    cityNameAr: "المحلة الكبرى",
    cityNameEn: "Al Mahalla Al Kobra",
  ),
  StateEntity(
    id: "194",
    governorateId: "8",
    cityNameAr: "كفر الزيات",
    cityNameEn: "Kafr El Zayat",
  ),
  StateEntity(
    id: "195",
    governorateId: "8",
    cityNameAr: "زفتى",
    cityNameEn: "Zefta",
  ),
  StateEntity(
    id: "196",
    governorateId: "8",
    cityNameAr: "السنطة",
    cityNameEn: "El Santa",
  ),
  StateEntity(
    id: "197",
    governorateId: "8",
    cityNameAr: "قطور",
    cityNameEn: "Qutour",
  ),
  StateEntity(
    id: "198",
    governorateId: "8",
    cityNameAr: "بسيون",
    cityNameEn: "Basion",
  ),
  StateEntity(
    id: "199",
    governorateId: "8",
    cityNameAr: "سمنود",
    cityNameEn: "Samannoud",
  ),
  StateEntity(
    id: "200",
    governorateId: "9",
    cityNameAr: "الإسماعيلية",
    cityNameEn: "Ismailia",
  ),
  StateEntity(
    id: "201",
    governorateId: "9",
    cityNameAr: "فايد",
    cityNameEn: "Fayed",
  ),
  StateEntity(
    id: "202",
    governorateId: "9",
    cityNameAr: "القنطرة شرق",
    cityNameEn: "Qantara Sharq",
  ),
  StateEntity(
    id: "203",
    governorateId: "9",
    cityNameAr: "القنطرة غرب",
    cityNameEn: "Qantara Gharb",
  ),
  StateEntity(
    id: "204",
    governorateId: "9",
    cityNameAr: "التل الكبير",
    cityNameEn: "El Tal El Kabier",
  ),
  StateEntity(
    id: "205",
    governorateId: "9",
    cityNameAr: "أبو صوير",
    cityNameEn: "Abu Sawir",
  ),
  StateEntity(
    id: "206",
    governorateId: "9",
    cityNameAr: "القصاصين الجديدة",
    cityNameEn: "Kasasien El Gedida",
  ),
  StateEntity(
    id: "207",
    governorateId: "9",
    cityNameAr: "نفيشة",
    cityNameEn: "Nefesha",
  ),
  StateEntity(
    id: "208",
    governorateId: "9",
    cityNameAr: "الشيخ زايد",
    cityNameEn: "Sheikh Zayed",
  ),
  StateEntity(
    id: "209",
    governorateId: "10",
    cityNameAr: "شبين الكوم",
    cityNameEn: "Shbeen El Koom",
  ),
  StateEntity(
    id: "210",
    governorateId: "10",
    cityNameAr: "مدينة السادات",
    cityNameEn: "Sadat City",
  ),
  StateEntity(
    id: "211",
    governorateId: "10",
    cityNameAr: "منوف",
    cityNameEn: "Menouf",
  ),
  StateEntity(
    id: "212",
    governorateId: "10",
    cityNameAr: "سرس الليان",
    cityNameEn: "Sars El-Layan",
  ),
  StateEntity(
    id: "213",
    governorateId: "10",
    cityNameAr: "أشمون",
    cityNameEn: "Ashmon",
  ),
  StateEntity(
    id: "214",
    governorateId: "10",
    cityNameAr: "الباجور",
    cityNameEn: "Al Bagor",
  ),
  StateEntity(
    id: "215",
    governorateId: "10",
    cityNameAr: "قويسنا",
    cityNameEn: "Quesna",
  ),
  StateEntity(
    id: "216",
    governorateId: "10",
    cityNameAr: "بركة السبع",
    cityNameEn: "Berkat El Saba",
  ),
  StateEntity(
    id: "217",
    governorateId: "10",
    cityNameAr: "تلا",
    cityNameEn: "Tala",
  ),
  StateEntity(
    id: "218",
    governorateId: "10",
    cityNameAr: "الشهداء",
    cityNameEn: "Al Shohada",
  ),
  StateEntity(
    id: "219",
    governorateId: "11",
    cityNameAr: "المنيا",
    cityNameEn: "Minya",
  ),
  StateEntity(
    id: "220",
    governorateId: "11",
    cityNameAr: "المنيا الجديدة",
    cityNameEn: "Minya El Gedida",
  ),
  StateEntity(
    id: "221",
    governorateId: "11",
    cityNameAr: "العدوة",
    cityNameEn: "El Adwa",
  ),
  StateEntity(
    id: "222",
    governorateId: "11",
    cityNameAr: "مغاغة",
    cityNameEn: "Magagha",
  ),
  StateEntity(
    id: "223",
    governorateId: "11",
    cityNameAr: "بني مزار",
    cityNameEn: "Bani Mazar",
  ),
  StateEntity(
    id: "224",
    governorateId: "11",
    cityNameAr: "مطاي",
    cityNameEn: "Mattay",
  ),
  StateEntity(
    id: "225",
    governorateId: "11",
    cityNameAr: "سمالوط",
    cityNameEn: "Samalut",
  ),
  StateEntity(
    id: "226",
    governorateId: "11",
    cityNameAr: "المدينة الفكرية",
    cityNameEn: "Madinat El Fekria",
  ),
  StateEntity(
    id: "227",
    governorateId: "11",
    cityNameAr: "ملوي",
    cityNameEn: "Meloy",
  ),
  StateEntity(
    id: "228",
    governorateId: "11",
    cityNameAr: "دير مواس",
    cityNameEn: "Deir Mawas",
  ),
  StateEntity(
    id: "229",
    governorateId: "11",
    cityNameAr: "ابو قرقاص",
    cityNameEn: "Abu Qurqas",
  ),
  StateEntity(
    id: "230",
    governorateId: "11",
    cityNameAr: "ارض سلطان",
    cityNameEn: "Ard Sultan",
  ),
  StateEntity(
    id: "231",
    governorateId: "12",
    cityNameAr: "بنها",
    cityNameEn: "Banha",
  ),
  StateEntity(
    id: "232",
    governorateId: "12",
    cityNameAr: "قليوب",
    cityNameEn: "Qalyub",
  ),
  StateEntity(
    id: "233",
    governorateId: "12",
    cityNameAr: "شبرا الخيمة",
    cityNameEn: "Shubra Al Khaimah",
  ),
  StateEntity(
    id: "234",
    governorateId: "12",
    cityNameAr: "القناطر الخيرية",
    cityNameEn: "Al Qanater Charity",
  ),
  StateEntity(
    id: "235",
    governorateId: "12",
    cityNameAr: "الخانكة",
    cityNameEn: "Khanka",
  ),
  StateEntity(
    id: "236",
    governorateId: "12",
    cityNameAr: "كفر شكر",
    cityNameEn: "Kafr Shukr",
  ),
  StateEntity(
    id: "237",
    governorateId: "12",
    cityNameAr: "طوخ",
    cityNameEn: "Tukh",
  ),
  StateEntity(
    id: "238",
    governorateId: "12",
    cityNameAr: "قها",
    cityNameEn: "Qaha",
  ),
  StateEntity(
    id: "239",
    governorateId: "12",
    cityNameAr: "العبور",
    cityNameEn: "Obour",
  ),
  StateEntity(
    id: "240",
    governorateId: "12",
    cityNameAr: "الخصوص",
    cityNameEn: "Khosous",
  ),
  StateEntity(
    id: "241",
    governorateId: "12",
    cityNameAr: "شبين القناطر",
    cityNameEn: "Shibin Al Qanater",
  ),
  StateEntity(
    id: "242",
    governorateId: "12",
    cityNameAr: "مسطرد",
    cityNameEn: "Mostorod",
  ),
  StateEntity(
    id: "243",
    governorateId: "13",
    cityNameAr: "الخارجة",
    cityNameEn: "El Kharga",
  ),
  StateEntity(
    id: "244",
    governorateId: "13",
    cityNameAr: "باريس",
    cityNameEn: "Paris",
  ),
  StateEntity(
    id: "245",
    governorateId: "13",
    cityNameAr: "موط",
    cityNameEn: "Mout",
  ),
  StateEntity(
    id: "246",
    governorateId: "13",
    cityNameAr: "الفرافرة",
    cityNameEn: "Farafra",
  ),
  StateEntity(
    id: "247",
    governorateId: "13",
    cityNameAr: "بلاط",
    cityNameEn: "Balat",
  ),
  StateEntity(
    id: "248",
    governorateId: "13",
    cityNameAr: "الداخلة",
    cityNameEn: "Dakhla",
  ),
  StateEntity(
    id: "249",
    governorateId: "14",
    cityNameAr: "السويس",
    cityNameEn: "Suez",
  ),
  StateEntity(
    id: "250",
    governorateId: "14",
    cityNameAr: "الجناين",
    cityNameEn: "Alganayen",
  ),
  StateEntity(
    id: "251",
    governorateId: "14",
    cityNameAr: "عتاقة",
    cityNameEn: "Ataqah",
  ),
  StateEntity(
    id: "252",
    governorateId: "14",
    cityNameAr: "العين السخنة",
    cityNameEn: "Ain Sokhna",
  ),
  StateEntity(
    id: "253",
    governorateId: "14",
    cityNameAr: "فيصل",
    cityNameEn: "Faysal",
  ),
  StateEntity(
    id: "254",
    governorateId: "15",
    cityNameAr: "أسوان",
    cityNameEn: "Aswan",
  ),
  StateEntity(
    id: "255",
    governorateId: "15",
    cityNameAr: "أسوان الجديدة",
    cityNameEn: "Aswan El Gedida",
  ),
  StateEntity(
    id: "256",
    governorateId: "15",
    cityNameAr: "دراو",
    cityNameEn: "Drau",
  ),
  StateEntity(
    id: "257",
    governorateId: "15",
    cityNameAr: "كوم أمبو",
    cityNameEn: "Kom Ombo",
  ),
  StateEntity(
    id: "258",
    governorateId: "15",
    cityNameAr: "نصر النوبة",
    cityNameEn: "Nasr Al Nuba",
  ),
  StateEntity(
    id: "259",
    governorateId: "15",
    cityNameAr: "كلابشة",
    cityNameEn: "Kalabsha",
  ),
  StateEntity(
    id: "260",
    governorateId: "15",
    cityNameAr: "إدفو",
    cityNameEn: "Edfu",
  ),
  StateEntity(
    id: "261",
    governorateId: "15",
    cityNameAr: "الرديسية",
    cityNameEn: "Al-Radisiyah",
  ),
  StateEntity(
    id: "262",
    governorateId: "15",
    cityNameAr: "البصيلية",
    cityNameEn: "Al Basilia",
  ),
  StateEntity(
    id: "263",
    governorateId: "15",
    cityNameAr: "السباعية",
    cityNameEn: "Al Sibaeia",
  ),
  StateEntity(
    id: "264",
    governorateId: "15",
    cityNameAr: "ابوسمبل السياحية",
    cityNameEn: "Abo Simbl Al Siyahia",
  ),
  StateEntity(
    id: "265",
    governorateId: "15",
    cityNameAr: "مرسى علم",
    cityNameEn: "Marsa Alam",
  ),
  StateEntity(
    id: "266",
    governorateId: "16",
    cityNameAr: "أسيوط",
    cityNameEn: "Assiut",
  ),
  StateEntity(
    id: "267",
    governorateId: "16",
    cityNameAr: "أسيوط الجديدة",
    cityNameEn: "Assiut El Gedida",
  ),
  StateEntity(
    id: "268",
    governorateId: "16",
    cityNameAr: "ديروط",
    cityNameEn: "Dayrout",
  ),
  StateEntity(
    id: "269",
    governorateId: "16",
    cityNameAr: "منفلوط",
    cityNameEn: "Manfalut",
  ),
  StateEntity(
    id: "270",
    governorateId: "16",
    cityNameAr: "القوصية",
    cityNameEn: "Qusiya",
  ),
  StateEntity(
    id: "271",
    governorateId: "16",
    cityNameAr: "أبنوب",
    cityNameEn: "Abnoub",
  ),
  StateEntity(
    id: "272",
    governorateId: "16",
    cityNameAr: "أبو تيج",
    cityNameEn: "Abu Tig",
  ),
  StateEntity(
    id: "273",
    governorateId: "16",
    cityNameAr: "الغنايم",
    cityNameEn: "El Ghanaim",
  ),
  StateEntity(
    id: "274",
    governorateId: "16",
    cityNameAr: "ساحل سليم",
    cityNameEn: "Sahel Selim",
  ),
  StateEntity(
    id: "275",
    governorateId: "16",
    cityNameAr: "البداري",
    cityNameEn: "El Badari",
  ),
  StateEntity(
    id: "276",
    governorateId: "16",
    cityNameAr: "صدفا",
    cityNameEn: "Sidfa",
  ),
  StateEntity(
    id: "277",
    governorateId: "17",
    cityNameAr: "بني سويف",
    cityNameEn: "Bani Sweif",
  ),
  StateEntity(
    id: "278",
    governorateId: "17",
    cityNameAr: "بني سويف الجديدة",
    cityNameEn: "Beni Suef El Gedida",
  ),
  StateEntity(
    id: "279",
    governorateId: "17",
    cityNameAr: "الواسطى",
    cityNameEn: "Al Wasta",
  ),
  StateEntity(
    id: "280",
    governorateId: "17",
    cityNameAr: "ناصر",
    cityNameEn: "Naser",
  ),
  StateEntity(
    id: "281",
    governorateId: "17",
    cityNameAr: "إهناسيا",
    cityNameEn: "Ehnasia",
  ),
  StateEntity(
    id: "282",
    governorateId: "17",
    cityNameAr: "ببا",
    cityNameEn: "Beba",
  ),
  StateEntity(
    id: "283",
    governorateId: "17",
    cityNameAr: "الفشن",
    cityNameEn: "Fashn",
  ),
  StateEntity(
    id: "284",
    governorateId: "17",
    cityNameAr: "سمسطا",
    cityNameEn: "Somasta",
  ),
  StateEntity(
    id: "285",
    governorateId: "17",
    cityNameAr: "الاباصيرى",
    cityNameEn: "Alabbaseri",
  ),
  StateEntity(
    id: "286",
    governorateId: "17",
    cityNameAr: "مقبل",
    cityNameEn: "Mokbel",
  ),
  StateEntity(
    id: "287",
    governorateId: "18",
    cityNameAr: "بورسعيد",
    cityNameEn: "PorSaid",
  ),
  StateEntity(
    id: "288",
    governorateId: "18",
    cityNameAr: "بورفؤاد",
    cityNameEn: "Port Fouad",
  ),
  StateEntity(
    id: "289",
    governorateId: "18",
    cityNameAr: "العرب",
    cityNameEn: "Alarab",
  ),
  StateEntity(
    id: "290",
    governorateId: "18",
    cityNameAr: "حى الزهور",
    cityNameEn: "Zohour",
  ),
  StateEntity(
    id: "291",
    governorateId: "18",
    cityNameAr: "حى الشرق",
    cityNameEn: "Alsharq",
  ),
  StateEntity(
    id: "292",
    governorateId: "18",
    cityNameAr: "حى الضواحى",
    cityNameEn: "Aldawahi",
  ),
  StateEntity(
    id: "293",
    governorateId: "18",
    cityNameAr: "حى المناخ",
    cityNameEn: "Almanakh",
  ),
  StateEntity(
    id: "294",
    governorateId: "18",
    cityNameAr: "حى مبارك",
    cityNameEn: "Mubarak",
  ),
  StateEntity(
    id: "295",
    governorateId: "19",
    cityNameAr: "دمياط",
    cityNameEn: "Damietta",
  ),
  StateEntity(
    id: "296",
    governorateId: "19",
    cityNameAr: "دمياط الجديدة",
    cityNameEn: "New Damietta",
  ),
  StateEntity(
    id: "297",
    governorateId: "19",
    cityNameAr: "رأس البر",
    cityNameEn: "Ras El Bar",
  ),
  StateEntity(
    id: "298",
    governorateId: "19",
    cityNameAr: "فارسكور",
    cityNameEn: "Faraskour",
  ),
  StateEntity(
    id: "299",
    governorateId: "19",
    cityNameAr: "الزرقا",
    cityNameEn: "Zarqa",
  ),
  StateEntity(
    id: "300",
    governorateId: "19",
    cityNameAr: "السرو",
    cityNameEn: "Alsaru",
  ),
  StateEntity(
    id: "301",
    governorateId: "19",
    cityNameAr: "الروضة",
    cityNameEn: "Alruwda",
  ),
  StateEntity(
    id: "302",
    governorateId: "19",
    cityNameAr: "كفر البطيخ",
    cityNameEn: "Kafr El-Batikh",
  ),
  StateEntity(
    id: "303",
    governorateId: "19",
    cityNameAr: "عزبة البرج",
    cityNameEn: "Azbet Al Burg",
  ),
  StateEntity(
    id: "304",
    governorateId: "19",
    cityNameAr: "ميت أبو غالب",
    cityNameEn: "Meet Abou Ghalib",
  ),
  StateEntity(
    id: "305",
    governorateId: "19",
    cityNameAr: "كفر سعد",
    cityNameEn: "Kafr Saad",
  ),
  StateEntity(
    id: "306",
    governorateId: "20",
    cityNameAr: "الزقازيق",
    cityNameEn: "Zagazig",
  ),
  StateEntity(
    id: "307",
    governorateId: "20",
    cityNameAr: "العاشر من رمضان",
    cityNameEn: "Al Ashr Men Ramadan",
  ),
  StateEntity(
    id: "308",
    governorateId: "20",
    cityNameAr: "منيا القمح",
    cityNameEn: "Minya Al Qamh",
  ),
  StateEntity(
    id: "309",
    governorateId: "20",
    cityNameAr: "بلبيس",
    cityNameEn: "Belbeis",
  ),
  StateEntity(
    id: "310",
    governorateId: "20",
    cityNameAr: "مشتول السوق",
    cityNameEn: "Mashtoul El Souq",
  ),
  StateEntity(
    id: "311",
    governorateId: "20",
    cityNameAr: "القنايات",
    cityNameEn: "Qenaiat",
  ),
  StateEntity(
    id: "312",
    governorateId: "20",
    cityNameAr: "أبو حماد",
    cityNameEn: "Abu Hammad",
  ),
  StateEntity(
    id: "313",
    governorateId: "20",
    cityNameAr: "القرين",
    cityNameEn: "El Qurain",
  ),
  StateEntity(
    id: "314",
    governorateId: "20",
    cityNameAr: "ههيا",
    cityNameEn: "Hehia",
  ),
  StateEntity(
    id: "315",
    governorateId: "20",
    cityNameAr: "أبو كبير",
    cityNameEn: "Abu Kabir",
  ),
  StateEntity(
    id: "316",
    governorateId: "20",
    cityNameAr: "فاقوس",
    cityNameEn: "Faccus",
  ),
  StateEntity(
    id: "317",
    governorateId: "20",
    cityNameAr: "الصالحية الجديدة",
    cityNameEn: "El Salihia El Gedida",
  ),
  StateEntity(
    id: "318",
    governorateId: "20",
    cityNameAr: "الإبراهيمية",
    cityNameEn: "Al Ibrahimiyah",
  ),
  StateEntity(
    id: "319",
    governorateId: "20",
    cityNameAr: "ديرب نجم",
    cityNameEn: "Deirb Negm",
  ),
  StateEntity(
    id: "320",
    governorateId: "20",
    cityNameAr: "كفر صقر",
    cityNameEn: "Kafr Saqr",
  ),
  StateEntity(
    id: "321",
    governorateId: "20",
    cityNameAr: "أولاد صقر",
    cityNameEn: "Awlad Saqr",
  ),
  StateEntity(
    id: "322",
    governorateId: "20",
    cityNameAr: "الحسينية",
    cityNameEn: "Husseiniya",
  ),
  StateEntity(
    id: "323",
    governorateId: "20",
    cityNameAr: "صان الحجر القبلية",
    cityNameEn: "San Alhajar Alqablia",
  ),
  StateEntity(
    id: "324",
    governorateId: "20",
    cityNameAr: "منشأة أبو عمر",
    cityNameEn: "Manshayat Abu Omar",
  ),
  StateEntity(
    id: "325",
    governorateId: "21",
    cityNameAr: "الطور",
    cityNameEn: "Al Toor",
  ),
  StateEntity(
    id: "326",
    governorateId: "21",
    cityNameAr: "شرم الشيخ",
    cityNameEn: "Sharm El-Shaikh",
  ),
  StateEntity(
    id: "327",
    governorateId: "21",
    cityNameAr: "دهب",
    cityNameEn: "Dahab",
  ),
  StateEntity(
    id: "328",
    governorateId: "21",
    cityNameAr: "نويبع",
    cityNameEn: "Nuweiba",
  ),
  StateEntity(
    id: "329",
    governorateId: "21",
    cityNameAr: "طابا",
    cityNameEn: "Taba",
  ),
  StateEntity(
    id: "330",
    governorateId: "21",
    cityNameAr: "سانت كاترين",
    cityNameEn: "Saint Catherine",
  ),
  StateEntity(
    id: "331",
    governorateId: "21",
    cityNameAr: "أبو رديس",
    cityNameEn: "Abu Redis",
  ),
  StateEntity(
    id: "332",
    governorateId: "21",
    cityNameAr: "أبو زنيمة",
    cityNameEn: "Abu Zenaima",
  ),
  StateEntity(
    id: "333",
    governorateId: "21",
    cityNameAr: "رأس سدر",
    cityNameEn: "Ras Sidr",
  ),
  StateEntity(
    id: "334",
    governorateId: "22",
    cityNameAr: "كفر الشيخ",
    cityNameEn: "Kafr El Sheikh",
  ),
  StateEntity(
    id: "335",
    governorateId: "22",
    cityNameAr: "وسط البلد كفر الشيخ",
    cityNameEn: "Kafr El Sheikh Downtown",
  ),
  StateEntity(
    id: "336",
    governorateId: "22",
    cityNameAr: "دسوق",
    cityNameEn: "Desouq",
  ),
  StateEntity(
    id: "337",
    governorateId: "22",
    cityNameAr: "فوه",
    cityNameEn: "Fooh",
  ),
  StateEntity(
    id: "338",
    governorateId: "22",
    cityNameAr: "مطوبس",
    cityNameEn: "Metobas",
  ),
  StateEntity(
    id: "339",
    governorateId: "22",
    cityNameAr: "برج البرلس",
    cityNameEn: "Burg Al Burullus",
  ),
  StateEntity(
    id: "340",
    governorateId: "22",
    cityNameAr: "بلطيم",
    cityNameEn: "Baltim",
  ),
  StateEntity(
    id: "341",
    governorateId: "22",
    cityNameAr: "مصيف بلطيم",
    cityNameEn: "Masief Baltim",
  ),
  StateEntity(
    id: "342",
    governorateId: "22",
    cityNameAr: "الحامول",
    cityNameEn: "Hamol",
  ),
  StateEntity(
    id: "343",
    governorateId: "22",
    cityNameAr: "بيلا",
    cityNameEn: "Bella",
  ),
  StateEntity(
    id: "344",
    governorateId: "22",
    cityNameAr: "الرياض",
    cityNameEn: "Riyadh",
  ),
  StateEntity(
    id: "345",
    governorateId: "22",
    cityNameAr: "سيدي سالم",
    cityNameEn: "Sidi Salm",
  ),
  StateEntity(
    id: "346",
    governorateId: "22",
    cityNameAr: "قلين",
    cityNameEn: "Qellen",
  ),
  StateEntity(
    id: "347",
    governorateId: "22",
    cityNameAr: "سيدي غازي",
    cityNameEn: "Sidi Ghazi",
  ),
  StateEntity(
    id: "348",
    governorateId: "23",
    cityNameAr: "مرسى مطروح",
    cityNameEn: "Marsa Matrouh",
  ),
  StateEntity(
    id: "349",
    governorateId: "23",
    cityNameAr: "الحمام",
    cityNameEn: "El Hamam",
  ),
  StateEntity(
    id: "350",
    governorateId: "23",
    cityNameAr: "العلمين",
    cityNameEn: "Alamein",
  ),
  StateEntity(
    id: "351",
    governorateId: "23",
    cityNameAr: "الضبعة",
    cityNameEn: "Dabaa",
  ),
  StateEntity(
    id: "352",
    governorateId: "23",
    cityNameAr: "النجيلة",
    cityNameEn: "Al-Nagila",
  ),
  StateEntity(
    id: "353",
    governorateId: "23",
    cityNameAr: "سيدي براني",
    cityNameEn: "Sidi Brani",
  ),
  StateEntity(
    id: "354",
    governorateId: "23",
    cityNameAr: "السلوم",
    cityNameEn: "Salloum",
  ),
  StateEntity(
    id: "355",
    governorateId: "23",
    cityNameAr: "سيوة",
    cityNameEn: "Siwa",
  ),
  StateEntity(
    id: "356",
    governorateId: "23",
    cityNameAr: "مارينا",
    cityNameEn: "Marina",
  ),
  StateEntity(
    id: "357",
    governorateId: "23",
    cityNameAr: "الساحل الشمالى",
    cityNameEn: "North Coast",
  ),
  StateEntity(
    id: "358",
    governorateId: "24",
    cityNameAr: "الأقصر",
    cityNameEn: "Luxor",
  ),
  StateEntity(
    id: "359",
    governorateId: "24",
    cityNameAr: "الأقصر الجديدة",
    cityNameEn: "New Luxor",
  ),
  StateEntity(
    id: "360",
    governorateId: "24",
    cityNameAr: "إسنا",
    cityNameEn: "Esna",
  ),
  StateEntity(
    id: "361",
    governorateId: "24",
    cityNameAr: "طيبة الجديدة",
    cityNameEn: "New Tiba",
  ),
  StateEntity(
    id: "362",
    governorateId: "24",
    cityNameAr: "الزينية",
    cityNameEn: "Al ziynia",
  ),
  StateEntity(
    id: "363",
    governorateId: "24",
    cityNameAr: "البياضية",
    cityNameEn: "Al Bayadieh",
  ),
  StateEntity(
    id: "364",
    governorateId: "24",
    cityNameAr: "القرنة",
    cityNameEn: "Al Qarna",
  ),
  StateEntity(
    id: "365",
    governorateId: "24",
    cityNameAr: "أرمنت",
    cityNameEn: "Armant",
  ),
  StateEntity(
    id: "366",
    governorateId: "24",
    cityNameAr: "الطود",
    cityNameEn: "Al Tud",
  ),
  StateEntity(
    id: "367",
    governorateId: "25",
    cityNameAr: "قنا",
    cityNameEn: "Qena",
  ),
  StateEntity(
    id: "368",
    governorateId: "25",
    cityNameAr: "قنا الجديدة",
    cityNameEn: "New Qena",
  ),
  StateEntity(
    id: "369",
    governorateId: "25",
    cityNameAr: "ابو طشت",
    cityNameEn: "Abu Tesht",
  ),
  StateEntity(
    id: "370",
    governorateId: "25",
    cityNameAr: "نجع حمادي",
    cityNameEn: "Nag Hammadi",
  ),
  StateEntity(
    id: "371",
    governorateId: "25",
    cityNameAr: "دشنا",
    cityNameEn: "Deshna",
  ),
  StateEntity(
    id: "372",
    governorateId: "25",
    cityNameAr: "الوقف",
    cityNameEn: "Alwaqf",
  ),
  StateEntity(
    id: "373",
    governorateId: "25",
    cityNameAr: "قفط",
    cityNameEn: "Qaft",
  ),
  StateEntity(
    id: "374",
    governorateId: "25",
    cityNameAr: "نقادة",
    cityNameEn: "Naqada",
  ),
  StateEntity(
    id: "375",
    governorateId: "25",
    cityNameAr: "فرشوط",
    cityNameEn: "Farshout",
  ),
  StateEntity(
    id: "376",
    governorateId: "25",
    cityNameAr: "قوص",
    cityNameEn: "Quos",
  ),
  StateEntity(
    id: "377",
    governorateId: "26",
    cityNameAr: "العريش",
    cityNameEn: "Arish",
  ),
  StateEntity(
    id: "378",
    governorateId: "26",
    cityNameAr: "الشيخ زويد",
    cityNameEn: "Sheikh Zowaid",
  ),
  StateEntity(
    id: "379",
    governorateId: "26",
    cityNameAr: "نخل",
    cityNameEn: "Nakhl",
  ),
  StateEntity(
    id: "380",
    governorateId: "26",
    cityNameAr: "رفح",
    cityNameEn: "Rafah",
  ),
  StateEntity(
    id: "381",
    governorateId: "26",
    cityNameAr: "بئر العبد",
    cityNameEn: "Bir al-Abed",
  ),
  StateEntity(
    id: "382",
    governorateId: "26",
    cityNameAr: "الحسنة",
    cityNameEn: "Al Hasana",
  ),
];
