// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/main_profile_screen/data/repository_imp/profile_screen_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:flower_app/core/common/result.dart' as _i6;
import 'package:flower_app/features/profile/main_profile_screen/data/data_source/profile_remote_data_source.dart'
    as _i4;
import 'package:flower_app/features/profile/main_profile_screen/data/model/edit_profile_response_dto.dart'
    as _i3;
import 'package:flower_app/features/profile/main_profile_screen/data/model/profile_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponseDTO_0 extends _i1.SmartFake
    implements _i2.ProfileResponseDTO {
  _FakeProfileResponseDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseDTO_1 extends _i1.SmartFake
    implements _i3.EditProfileResponseDTO {
  _FakeEditProfileResponseDTO_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i4.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProfileResponseDTO> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue:
            _i5.Future<_i2.ProfileResponseDTO>.value(_FakeProfileResponseDTO_0(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ProfileResponseDTO>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.EditProfileResponseDTO> editProfile(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [data],
        ),
        returnValue: _i5.Future<_i3.EditProfileResponseDTO>.value(
            _FakeEditProfileResponseDTO_1(
          this,
          Invocation.method(
            #editProfile,
            [data],
          ),
        )),
      ) as _i5.Future<_i3.EditProfileResponseDTO>);

  @override
  _i5.Future<_i6.Result<String?>> uploadPhoto(_i7.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i5.Future<_i6.Result<String?>>.value(
            _i8.dummyValue<_i6.Result<String?>>(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i5.Future<_i6.Result<String?>>);
}
