// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/addresses/data/data_source/user_addresses_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i23;

import 'package:dio/dio.dart' as _i30;
import 'package:flower_app/core/api/api_client.dart' as _i22;
import 'package:flower_app/features/addresses/data/model/user_addresses_dto.dart'
    as _i15;
import 'package:flower_app/features/auth/data/model/forget_response_password_dto.dart'
    as _i4;
import 'package:flower_app/features/auth/data/model/reset_password_dto.dart'
    as _i6;
import 'package:flower_app/features/auth/data/model/sign_up_response_dto.dart'
    as _i2;
import 'package:flower_app/features/auth/data/model/verify_email_response_dto.dart'
    as _i5;
import 'package:flower_app/features/auth/domain/entity/sign_in_request.dart'
    as _i25;
import 'package:flower_app/features/auth/domain/entity/sign_up_request.dart'
    as _i24;
import 'package:flower_app/features/cart/data/models/create_cart_reponse.dart'
    as _i31;
import 'package:flower_app/features/cart/data/models/create_cart_request.dart'
    as _i32;
import 'package:flower_app/features/cart/data/models/delet_cart_item_dto/delete_cart_response_dto.dart'
    as _i33;
import 'package:flower_app/features/cart/data/models/update_product_quantity/update_cart_quantity_request.dart'
    as _i35;
import 'package:flower_app/features/cart/data/models/update_product_quantity/update_cart_quantity_response_dto.dart'
    as _i34;
import 'package:flower_app/features/cart/data/models/user_cart_response/user_cart_response_model.dart'
    as _i14;
import 'package:flower_app/features/checkout/data/model/addresses_response_dto.dart'
    as _i36;
import 'package:flower_app/features/checkout/data/model/checkout_cash_response_model.dart'
    as _i17;
import 'package:flower_app/features/checkout/data/model/credit_card_request_model.dart'
    as _i37;
import 'package:flower_app/features/checkout/data/model/credit_card_response_model.dart'
    as _i16;
import 'package:flower_app/features/home/best_seller_products/data/model/BestSellerProductsModel.dart'
    as _i26;
import 'package:flower_app/features/home/categories/data/model/categories_response_model.dart'
    as _i12;
import 'package:flower_app/features/home/categories/data/model/specific_categories_response_model.dart'
    as _i11;
import 'package:flower_app/features/home/home_tab/data/model/category_response_dto.dart'
    as _i7;
import 'package:flower_app/features/home/home_tab/data/model/occasion_response_dto.dart'
    as _i8;
import 'package:flower_app/features/home/occasions/data/model/occasions_dto.dart'
    as _i9;
import 'package:flower_app/features/home/occasions/data/model/products_response_dto.dart'
    as _i10;
import 'package:flower_app/features/home/products_details/data/models/products_details_models.dart'
    as _i27;
import 'package:flower_app/features/profile/main_profile_screen/data/model/change_password_model.dart'
    as _i13;
import 'package:flower_app/features/profile/main_profile_screen/data/model/change_password_request_model.dart'
    as _i28;
import 'package:flower_app/features/profile/main_profile_screen/data/model/delete_notifiacation_response_model.dart'
    as _i21;
import 'package:flower_app/features/profile/main_profile_screen/data/model/edit_profile_response_dto.dart'
    as _i29;
import 'package:flower_app/features/profile/main_profile_screen/data/model/get_all_notification_response_model.dart'
    as _i19;
import 'package:flower_app/features/profile/main_profile_screen/data/model/get_notification_details_model.dart'
    as _i20;
import 'package:flower_app/features/profile/main_profile_screen/data/model/profile_response_dto.dart'
    as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseDTO_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDTO {
  _FakeSignUpResponseDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetResponsePasswordDto_2 extends _i1.SmartFake
    implements _i4.ForgetResponsePasswordDto {
  _FakeForgetResponsePasswordDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyEmailResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyEmailResponseDto {
  _FakeVerifyEmailResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDTO_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDTO {
  _FakeResetPasswordResponseDTO_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryResponseDTO_5 extends _i1.SmartFake
    implements _i7.CategoryResponseDTO {
  _FakeCategoryResponseDTO_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOccasionResponseDTO_6 extends _i1.SmartFake
    implements _i8.OccasionResponseDTO {
  _FakeOccasionResponseDTO_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOccasionsResponseDTO_7 extends _i1.SmartFake
    implements _i9.OccasionsResponseDTO {
  _FakeOccasionsResponseDTO_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductsResponseDTO_8 extends _i1.SmartFake
    implements _i10.ProductsResponseDTO {
  _FakeProductsResponseDTO_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpecificCategoriesResponseModel_9 extends _i1.SmartFake
    implements _i11.SpecificCategoriesResponseModel {
  _FakeSpecificCategoriesResponseModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoriesResponseModel_10 extends _i1.SmartFake
    implements _i12.CategoriesResponseModel {
  _FakeCategoriesResponseModel_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordModel_11 extends _i1.SmartFake
    implements _i13.ChangePasswordModel {
  _FakeChangePasswordModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCartResponseModel_12 extends _i1.SmartFake
    implements _i14.UserCartResponseModel {
  _FakeUserCartResponseModel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserAddressesDTO_13 extends _i1.SmartFake
    implements _i15.UserAddressesDTO {
  _FakeUserAddressesDTO_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreditCardResponseModel_14 extends _i1.SmartFake
    implements _i16.CreditCardResponseModel {
  _FakeCreditCardResponseModel_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckoutCashResponseModel_15 extends _i1.SmartFake
    implements _i17.CheckoutCashResponseModel {
  _FakeCheckoutCashResponseModel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponseDTO_16 extends _i1.SmartFake
    implements _i18.ProfileResponseDTO {
  _FakeProfileResponseDTO_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllNotificationResponseModel_17 extends _i1.SmartFake
    implements _i19.GetAllNotificationResponseModel {
  _FakeGetAllNotificationResponseModel_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNotificationDetailsModel_18 extends _i1.SmartFake
    implements _i20.GetNotificationDetailsModel {
  _FakeGetNotificationDetailsModel_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteNotificationResponseModel_19 extends _i1.SmartFake
    implements _i21.DeleteNotificationResponseModel {
  _FakeDeleteNotificationResponseModel_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i22.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<_i2.SignUpResponseDTO> signUp(_i24.SignUpRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [data],
        ),
        returnValue:
            _i23.Future<_i2.SignUpResponseDTO>.value(_FakeSignUpResponseDTO_0(
          this,
          Invocation.method(
            #signUp,
            [data],
          ),
        )),
      ) as _i23.Future<_i2.SignUpResponseDTO>);

  @override
  _i23.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>> signIn(
          _i25.SignInRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [data],
        ),
        returnValue: _i23.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>.value(
            _FakeHttpResponse_1<_i2.SignUpResponseDTO>(
          this,
          Invocation.method(
            #signIn,
            [data],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i2.SignUpResponseDTO>>);

  @override
  _i23.Future<_i4.ForgetResponsePasswordDto> forgetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [data],
        ),
        returnValue: _i23.Future<_i4.ForgetResponsePasswordDto>.value(
            _FakeForgetResponsePasswordDto_2(
          this,
          Invocation.method(
            #forgetPassword,
            [data],
          ),
        )),
      ) as _i23.Future<_i4.ForgetResponsePasswordDto>);

  @override
  _i23.Future<_i5.VerifyEmailResponseDto> verifyEmail(
          Map<String, String>? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue: _i23.Future<_i5.VerifyEmailResponseDto>.value(
            _FakeVerifyEmailResponseDto_3(
          this,
          Invocation.method(
            #verifyEmail,
            [code],
          ),
        )),
      ) as _i23.Future<_i5.VerifyEmailResponseDto>);

  @override
  _i23.Future<_i6.ResetPasswordResponseDTO> resetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [data],
        ),
        returnValue: _i23.Future<_i6.ResetPasswordResponseDTO>.value(
            _FakeResetPasswordResponseDTO_4(
          this,
          Invocation.method(
            #resetPassword,
            [data],
          ),
        )),
      ) as _i23.Future<_i6.ResetPasswordResponseDTO>);

  @override
  _i23.Future<_i3.HttpResponse<_i26.BestSellerProductsModel>> getBestSeller() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBestSeller,
          [],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i26.BestSellerProductsModel>>.value(
                _FakeHttpResponse_1<_i26.BestSellerProductsModel>(
          this,
          Invocation.method(
            #getBestSeller,
            [],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i26.BestSellerProductsModel>>);

  @override
  _i23.Future<_i7.CategoryResponseDTO> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i23.Future<_i7.CategoryResponseDTO>.value(
            _FakeCategoryResponseDTO_5(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i23.Future<_i7.CategoryResponseDTO>);

  @override
  _i23.Future<_i8.OccasionResponseDTO> getOccasion() => (super.noSuchMethod(
        Invocation.method(
          #getOccasion,
          [],
        ),
        returnValue: _i23.Future<_i8.OccasionResponseDTO>.value(
            _FakeOccasionResponseDTO_6(
          this,
          Invocation.method(
            #getOccasion,
            [],
          ),
        )),
      ) as _i23.Future<_i8.OccasionResponseDTO>);

  @override
  _i23.Future<_i9.OccasionsResponseDTO> getOccasions() => (super.noSuchMethod(
        Invocation.method(
          #getOccasions,
          [],
        ),
        returnValue: _i23.Future<_i9.OccasionsResponseDTO>.value(
            _FakeOccasionsResponseDTO_7(
          this,
          Invocation.method(
            #getOccasions,
            [],
          ),
        )),
      ) as _i23.Future<_i9.OccasionsResponseDTO>);

  @override
  _i23.Future<_i10.ProductsResponseDTO> getProductsByOccasion(
          String? occasionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByOccasion,
          [occasionId],
        ),
        returnValue: _i23.Future<_i10.ProductsResponseDTO>.value(
            _FakeProductsResponseDTO_8(
          this,
          Invocation.method(
            #getProductsByOccasion,
            [occasionId],
          ),
        )),
      ) as _i23.Future<_i10.ProductsResponseDTO>);

  @override
  _i23.Future<_i11.SpecificCategoriesResponseModel> getProductsByFilter(
          String? sort) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByFilter,
          [sort],
        ),
        returnValue: _i23.Future<_i11.SpecificCategoriesResponseModel>.value(
            _FakeSpecificCategoriesResponseModel_9(
          this,
          Invocation.method(
            #getProductsByFilter,
            [sort],
          ),
        )),
      ) as _i23.Future<_i11.SpecificCategoriesResponseModel>);

  @override
  _i23.Future<_i3.HttpResponse<_i27.ProductsDetailsModels>> getProductDetails(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetails,
          [id],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i27.ProductsDetailsModels>>.value(
                _FakeHttpResponse_1<_i27.ProductsDetailsModels>(
          this,
          Invocation.method(
            #getProductDetails,
            [id],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i27.ProductsDetailsModels>>);

  @override
  _i23.Future<_i12.CategoriesResponseModel> getAllCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i23.Future<_i12.CategoriesResponseModel>.value(
            _FakeCategoriesResponseModel_10(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i23.Future<_i12.CategoriesResponseModel>);

  @override
  _i23.Future<_i11.SpecificCategoriesResponseModel> getSpecificCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificCategory,
          [categoryId],
        ),
        returnValue: _i23.Future<_i11.SpecificCategoriesResponseModel>.value(
            _FakeSpecificCategoriesResponseModel_9(
          this,
          Invocation.method(
            #getSpecificCategory,
            [categoryId],
          ),
        )),
      ) as _i23.Future<_i11.SpecificCategoriesResponseModel>);

  @override
  _i23.Future<_i3.HttpResponse<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<void>>.value(_FakeHttpResponse_1<void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<void>>);

  @override
  _i23.Future<_i13.ChangePasswordModel> changePassword(
    _i28.ChangePasswordRequestModel? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            data,
            token,
          ],
        ),
        returnValue: _i23.Future<_i13.ChangePasswordModel>.value(
            _FakeChangePasswordModel_11(
          this,
          Invocation.method(
            #changePassword,
            [
              data,
              token,
            ],
          ),
        )),
      ) as _i23.Future<_i13.ChangePasswordModel>);

  @override
  _i23.Future<_i3.HttpResponse<_i29.EditProfileResponseDTO>> editProfile(
    String? token,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [
            token,
            data,
          ],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i29.EditProfileResponseDTO>>.value(
                _FakeHttpResponse_1<_i29.EditProfileResponseDTO>(
          this,
          Invocation.method(
            #editProfile,
            [
              token,
              data,
            ],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i29.EditProfileResponseDTO>>);

  @override
  _i23.Future<String?> uploadPhoto(
    String? token,
    _i30.FormData? formData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [
            token,
            formData,
          ],
        ),
        returnValue: _i23.Future<String?>.value(),
      ) as _i23.Future<String?>);

  @override
  _i23.Future<_i3.HttpResponse<_i31.CreateCartResponse>> addProductToCart(
    String? token,
    _i32.CreateCartRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductToCart,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i31.CreateCartResponse>>.value(
                _FakeHttpResponse_1<_i31.CreateCartResponse>(
          this,
          Invocation.method(
            #addProductToCart,
            [
              token,
              request,
            ],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i31.CreateCartResponse>>);

  @override
  _i23.Future<_i14.UserCartResponseModel> getUserCart(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCart,
          [token],
        ),
        returnValue: _i23.Future<_i14.UserCartResponseModel>.value(
            _FakeUserCartResponseModel_12(
          this,
          Invocation.method(
            #getUserCart,
            [token],
          ),
        )),
      ) as _i23.Future<_i14.UserCartResponseModel>);

  @override
  _i23.Future<_i3.HttpResponse<_i33.DeleteCartResponseDTO>> deleteCartItem(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCartItem,
          [
            token,
            id,
          ],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i33.DeleteCartResponseDTO>>.value(
                _FakeHttpResponse_1<_i33.DeleteCartResponseDTO>(
          this,
          Invocation.method(
            #deleteCartItem,
            [
              token,
              id,
            ],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i33.DeleteCartResponseDTO>>);

  @override
  _i23.Future<
      _i3.HttpResponse<_i34.UpdateCartQuantityResponseDTO>> updateCartQuantity(
    String? token,
    String? id,
    _i35.UpdateCartQuantityRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartQuantity,
          [
            token,
            id,
            request,
          ],
        ),
        returnValue: _i23
            .Future<_i3.HttpResponse<_i34.UpdateCartQuantityResponseDTO>>.value(
            _FakeHttpResponse_1<_i34.UpdateCartQuantityResponseDTO>(
          this,
          Invocation.method(
            #updateCartQuantity,
            [
              token,
              id,
              request,
            ],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i34.UpdateCartQuantityResponseDTO>>);

  @override
  _i23.Future<_i15.UserAddressesDTO> getUserAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getUserAddresses,
          [],
        ),
        returnValue:
            _i23.Future<_i15.UserAddressesDTO>.value(_FakeUserAddressesDTO_13(
          this,
          Invocation.method(
            #getUserAddresses,
            [],
          ),
        )),
      ) as _i23.Future<_i15.UserAddressesDTO>);

  @override
  _i23.Future<_i3.HttpResponse<_i36.AddressesResponseDTO>> getAddresses(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddresses,
          [token],
        ),
        returnValue:
            _i23.Future<_i3.HttpResponse<_i36.AddressesResponseDTO>>.value(
                _FakeHttpResponse_1<_i36.AddressesResponseDTO>(
          this,
          Invocation.method(
            #getAddresses,
            [token],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i36.AddressesResponseDTO>>);

  @override
  _i23.Future<_i3.HttpResponse<_i15.UserAddressesDTO>> deleteUserAddress(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserAddress,
          [id],
        ),
        returnValue: _i23.Future<_i3.HttpResponse<_i15.UserAddressesDTO>>.value(
            _FakeHttpResponse_1<_i15.UserAddressesDTO>(
          this,
          Invocation.method(
            #deleteUserAddress,
            [id],
          ),
        )),
      ) as _i23.Future<_i3.HttpResponse<_i15.UserAddressesDTO>>);

  @override
  _i23.Future<void> saveUserAddress(
    String? token,
    Map<String, dynamic>? addressJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserAddress,
          [
            token,
            addressJson,
          ],
        ),
        returnValue: _i23.Future<void>.value(),
        returnValueForMissingStub: _i23.Future<void>.value(),
      ) as _i23.Future<void>);

  @override
  _i23.Future<_i16.CreditCardResponseModel> checkoutCredit(
    _i37.CreditCardRequestModel? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkoutCredit,
          [
            data,
            token,
          ],
        ),
        returnValue: _i23.Future<_i16.CreditCardResponseModel>.value(
            _FakeCreditCardResponseModel_14(
          this,
          Invocation.method(
            #checkoutCredit,
            [
              data,
              token,
            ],
          ),
        )),
      ) as _i23.Future<_i16.CreditCardResponseModel>);

  @override
  _i23.Future<_i17.CheckoutCashResponseModel> checkoutCash(
    _i37.CreditCardRequestModel? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkoutCash,
          [
            data,
            token,
          ],
        ),
        returnValue: _i23.Future<_i17.CheckoutCashResponseModel>.value(
            _FakeCheckoutCashResponseModel_15(
          this,
          Invocation.method(
            #checkoutCash,
            [
              data,
              token,
            ],
          ),
        )),
      ) as _i23.Future<_i17.CheckoutCashResponseModel>);

  @override
  _i23.Future<_i15.UserAddressesDTO> updateAddress(
    String? id,
    Map<String, dynamic>? address,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [
            id,
            address,
          ],
        ),
        returnValue:
            _i23.Future<_i15.UserAddressesDTO>.value(_FakeUserAddressesDTO_13(
          this,
          Invocation.method(
            #updateAddress,
            [
              id,
              address,
            ],
          ),
        )),
      ) as _i23.Future<_i15.UserAddressesDTO>);

  @override
  _i23.Future<_i18.ProfileResponseDTO> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i23.Future<_i18.ProfileResponseDTO>.value(
            _FakeProfileResponseDTO_16(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i23.Future<_i18.ProfileResponseDTO>);

  @override
  _i23.Future<_i19.GetAllNotificationResponseModel> getAllNotifications(
    String? token,
    String? sort,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotifications,
          [
            token,
            sort,
          ],
        ),
        returnValue: _i23.Future<_i19.GetAllNotificationResponseModel>.value(
            _FakeGetAllNotificationResponseModel_17(
          this,
          Invocation.method(
            #getAllNotifications,
            [
              token,
              sort,
            ],
          ),
        )),
      ) as _i23.Future<_i19.GetAllNotificationResponseModel>);

  @override
  _i23.Future<_i20.GetNotificationDetailsModel> getNotificationDetails(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationDetails,
          [
            token,
            id,
          ],
        ),
        returnValue: _i23.Future<_i20.GetNotificationDetailsModel>.value(
            _FakeGetNotificationDetailsModel_18(
          this,
          Invocation.method(
            #getNotificationDetails,
            [
              token,
              id,
            ],
          ),
        )),
      ) as _i23.Future<_i20.GetNotificationDetailsModel>);

  @override
  _i23.Future<_i21.DeleteNotificationResponseModel> deleteNotification(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [
            token,
            id,
          ],
        ),
        returnValue: _i23.Future<_i21.DeleteNotificationResponseModel>.value(
            _FakeDeleteNotificationResponseModel_19(
          this,
          Invocation.method(
            #deleteNotification,
            [
              token,
              id,
            ],
          ),
        )),
      ) as _i23.Future<_i21.DeleteNotificationResponseModel>);
}
